/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/

import React from "react";
import {CategoryTreeComponent} from "../../../../gen/components/rootContainer/mainView/authorView/CategoryTreeComponent";
import {CardViewComponent} from "../../../../gen/components/rootContainer/mainView/authorView/CardViewComponent";

export function uiElement(props) {
    return <div className="categoryCardSplitView">
        <CategoryTreeComponent language={props.language}/>
        <CardViewComponent language={props.language} categoryTree={props.categoryTree} />
    </div>
}


/******* S.D.G. *******/



