/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {route} from "../../../../gen/common/ActionFunctions";
import React from "react";
import {DeleteBoxComponent} from "../../../../gen/components/rootContainer/mainView/dashboardView/DeleteBoxComponent";
import {BoxListItemComponent} from "../../../../gen/components/rootContainer/mainView/dashboardView/BoxListItemComponent";

export function uiElement(props) {
    return <div>
        <div className="bottomMargin">
            <DeleteBoxComponent language={props.language}/>
            <div>
                {
                    props.boxList ?
                        props.boxList.map((item) => <BoxListItemComponent key={item.boxId}  {...item} language={props.language}/>) :
                        []
                }
            </div>
            <a
                className="tile box-create"
                onClick={() => route("#box/create")}
            >
                <div className="text-center">
                    <i className="fas fa-plus-circle fa-2x"/>
                </div>
            </a>
        </div>
    </div>
}


/******* S.D.G. *******/



