/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { BoxListItem } from "./dashboardView/BoxListItem";
import { DeleteBox } from "./dashboardView/DeleteBox";
import {route} from "../../../../gen/common/ActionFunctions";

export const DashboardView = (props) => {
	return <div id="dashboard">
		<div className="bottomMargin">
			<DeleteBox {...props.deleteBox} language={props.language}/>
			<div>
				{
					props.boxList ?
						props.boxList.map((item) => <BoxListItem key={item.boxId}  {...item} language={props.language}/>) :
						[]
				}
			</div>
			<a
				className="tile box-create"
				onClick={() => route("#box/create")}
			>
				<div className="text-center">
					<i className="fas fa-plus-circle fa-2x"/>
				</div>
			</a>
		</div>
	</div>
}



/******* S.D.G. *******/



