/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {a, boxListItem, deleteBox, div, i} from "../../../../gen/components/ReactHelper";
import {route} from "../../../../gen/common/ActionFunctions";

export function uiElement(attributes) {
    return div({}, [
        div({class: "bottomMargin"}, []),
        deleteBox({}),
        div({}, [
            attributes.boxList ? attributes.boxList.map((item) => boxListItem({...item, language: attributes.language})) : []
        ]),
        a({
            class: "tile box-create",
            onClick: () => route("#box/create")
        }, [
            div({class: "text-center"}, [
                i({class: "fas fa-plus-circle fa-2x"})
            ])
        ])
    ]);
}


/******* S.D.G. *******/



