/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../app/Texts";
import {forgotPassword, usernameForgotPasswordChanged} from "../../../../gen/password/ActionFunctions";
import {route} from "../../../../gen/common/ActionFunctions";


export const ForgotPasswordView = (props) => {
	return <div className="center">
		<div className="form">
			<h1>{Texts.forgotPassword.title[props.language]}</h1>
			<div className="line">
				<label htmlFor="username">{Texts.forgotPassword.username[props.language]}</label>
				<input
					id="username"
					value={props.username}
					type="text"
					autoComplete="new-password"
					onChange={(e) => usernameForgotPasswordChanged(e.target.value)}
				/>
			</div>
			<div className="moreMarginLine hCenter">
				<button onClick={forgotPassword}
						disabled={!props.username || props.username && props.username.length === 0}>
					{Texts.forgotPassword.submit[props.language]}
				</button>
				<button
					onClick={() => route("#")}>{Texts.forgotPassword.cancel[props.language]}</button>
			</div>
		</div>
	</div>
}



/******* S.D.G. *******/



