/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/

import React from "react";
import {login, passwordChanged, toggleSaveInLocalStorage, usernameChanged} from "../../../../gen/login/ActionFunctions";
import {Texts} from "../../../app/Texts";
import {route} from "../../../../gen/common/ActionFunctions";
import CryptoJS from "crypto-js";

export function uiElement(attributes) {
    return <div className="center form">
        <h1>{Texts.login.title[attributes.language]}</h1>
        <div className="line">
            <label htmlFor="username">
                {Texts.login.username[attributes.language]}
            </label>
            <input
                id="username"
                type="text"
                onChange={(e) => usernameChanged(e.target.value)}
            />
            <a onClick={() => route("#registration")}>{Texts.login.registration[attributes.language]}</a>
        </div>
        <div className="line">
            <label htmlFor="password">
                {Texts.login.password[attributes.language]}
            </label>
            <input
                id="password"
                type="password"
                onChange={(e) => passwordChanged(CryptoJS.MD5(e.target.value).toString())}
            />
            <a onClick={() => route("#forgotpassword")}>{Texts.login.forgotPassword[attributes.language]}</a>
        </div>
        <div className="line">
            <input
                id="saveInLocalStorage"
                type="checkbox"
                onChange={toggleSaveInLocalStorage}
            />
            <label htmlFor="saveInLocalStorage">
                {Texts.login.saveInLocalStorage[attributes.language]}
            </label>
            <div className="small-font">{Texts.login.saveInLocalStorageHint[attributes.language]}</div>
        </div>
        <div className="moreMarginLine hCenter">
            <button
                className="primary"
                onClick={login}
            >
                {Texts.login.signin[attributes.language]}
            </button>
        </div>
    </div>
}


/******* S.D.G. *******/



