/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../app/Texts";
import {login, passwordChanged, toggleSaveInLocalStorage, usernameChanged} from "../../../../gen/login/ActionFunctions";
import {route} from "../../../../gen/common/ActionFunctions";
import CryptoJS from "crypto-js";


export const LoginView = (props) => {
	return <div className="center form">
		<h1>{Texts.login.title[props.language]}</h1>
		<div className="line">
			<label htmlFor="username">
				{Texts.login.username[props.language]}
			</label>
			<input
				id="username"
				type="text"
				onChange={(e) => usernameChanged(e.target.value)}
			/>
			<a id="registration" onClick={() => route("#registration")}>{Texts.login.registration[props.language]}</a>
		</div>
		<div className="line">
			<label htmlFor="password">
				{Texts.login.password[props.language]}
			</label>
			<input
				id="password"
				type="password"
				onChange={(e) => passwordChanged(CryptoJS.MD5(e.target.value).toString())}
			/>
			<a onClick={() => route("#forgotpassword")}>{Texts.login.forgotPassword[props.language]}</a>
		</div>
		<div className="line">
			<input
				id="saveInLocalStorage"
				type="checkbox"
				onChange={toggleSaveInLocalStorage}
			/>
			<label htmlFor="saveInLocalStorage">
				{Texts.login.saveInLocalStorage[props.language]}
			</label>
			<div className="small-font">{Texts.login.saveInLocalStorageHint[props.language]}</div>
		</div>
		<div className="moreMarginLine hCenter">
			<button
				className="primary"
				id="login"
				onClick={login}
			>
				{Texts.login.signin[props.language]}
			</button>
		</div>
	</div>
}



/******* S.D.G. *******/



