/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div, h1, label, input, table, tbody, ul, li, tr, td } from "../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	return div({}, [
		h1({}, ["PROFILEVIEW"]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "username"
			}, ["USERNAME"]), 
			input({
				id: "username",
				value: attributes.username, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.username])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "email"
			}, ["EMAIL"]), 
			input({
				id: "email",
				value: attributes.email, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.email])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "role"
			}, ["ROLE"]), 
			input({
				id: "role",
				value: attributes.role, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.role])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "showDeleteUserDialog"
			}, ["SHOWDELETEUSERDIALOG"]), 
			input({
				id: "showDeleteUserDialog",
				value: attributes.showDeleteUserDialog, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.showDeleteUserDialog])
		])
	]);
}



/******* S.D.G. *******/



