/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../app/Texts";
import {deleteUser, deleteUserCancel, deleteUserClick} from "../../../../gen/profile/ActionFunctions";
import {route} from "../../../../gen/common/ActionFunctions";


export const ProfileView = (props) => {
	if (props.role === undefined) {
		return null;
	}
	return <div className="center-wide">
		{props.showDeleteUserDialog === true ?
			<div className="modal">
				<div className="modalContent danger">
					<h2>{Texts.profile.confirmDelete.title[props.language]}</h2>
					<div className="message">{Texts.profile.confirmDelete.message[props.language]}</div>
					<button
						className="yes"
						onClick={deleteUser}
					>
						{Texts.profile.confirmDelete.ok[props.language]}
					</button>
					<button
						onClick={deleteUserCancel}
					>
						{Texts.profile.confirmDelete.cancel[props.language]}
					</button>
				</div>
			</div> :
			null
		}
		<div className="form">
			<h1>
				<button onClick={() => route("#dashboard")}><i className="fa fa-arrow-left"/></button>
				{Texts.profile.title[props.language]}
			</h1>
			<div className="line">
				<label htmlFor="username">{Texts.profile.username[props.language]}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.username}
						id="username"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="line">
				<label htmlFor="email">{Texts.profile.email[props.language]}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.email}
						id="email"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="line">
				<label htmlFor="role">{Texts.profile.role[props.language]}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={Texts.profile.role[props.role][props.language]}
						id="role"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="moreMarginLine hCenter">
				<button
					className="danger"
					onClick={deleteUserClick}
				>
					{Texts.profile.delete[props.language]}
				</button>
			</div>
		</div>
	</div>
}



/******* S.D.G. *******/



