/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/





import { div, h1, label, input, table, tbody, ul, li, tr, td } from "../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	console.log("REGISTRATIONVIEW", attributes);
	return div({}, [
		h1({}, ["REGISTRATIONVIEW"]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "displayUsernameSpinner"
			}, ["DISPLAYUSERNAMESPINNER"]), 
			input({
				id: "displayUsernameSpinner",
				value: attributes.displayUsernameSpinner, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.displayUsernameSpinner])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "available"
			}, ["AVAILABLE"]), 
			input({
				id: "available",
				value: attributes.available, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.available])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "username"
			}, ["USERNAME"]), 
			input({
				id: "username",
				value: attributes.username, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.username])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "email"
			}, ["EMAIL"]), 
			input({
				id: "email",
				value: attributes.email, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.email])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "emailInvalid"
			}, ["EMAILINVALID"]), 
			input({
				id: "emailInvalid",
				value: attributes.emailInvalid, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.emailInvalid])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "passwordMismatch"
			}, ["PASSWORDMISMATCH"]), 
			input({
				id: "passwordMismatch",
				value: attributes.passwordMismatch, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.passwordMismatch])
		])
	]);
}



/******* S.D.G. *******/



