/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { UserListItem } from "./userListView/UserListItem";

export const UserListView = (props) => {
	const json = JSON.stringify(props, null, '\t');
	return <div>
		{ props.userList ? props.userList.map(i => <UserListItem {...i} />) : [] }
		<div>{props.showDeleteUserDialog}</div>
		<div>{props.usernameToBeDeleted}</div>
		<pre>{json}</pre>
	</div> 
}



/******* S.D.G. *******/



