/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import AbstractPasswordRepetitionChangedCommand from "../../../gen/password/commands/AbstractPasswordRepetitionChangedCommand";

export default class PasswordRepetitionChangedCommand extends AbstractPasswordRepetitionChangedCommand {
    execute() {
        this.commandData.passwordMismatch = this.commandData.password !== this.commandData.passwordRepetition;
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



