/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractResetPasswordCommand from "../../../gen/password/commands/AbstractResetPasswordCommand";
import * as AppUtils from "../../app/AppUtils";

export default class ResetPasswordCommand extends AbstractResetPasswordCommand {

    validateCommandData(data) {
    	//data.password is mandatory String
    	//data.token is mandatory String
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.hash = "#";
        data.message = AppUtils.createInfoMessage("passwordReset");
        this.addOkOutcome(data);
        resolve(data);
    }
    handleError(data, resolve) {
        data.hash = "#";
        this.addErrorOutcome(data);
        data.message = data.error;
        resolve(data);
    }
}




/******* S.D.G. *******/

