/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUsernameForgotPasswordChangedCommand from "../../../gen/password/commands/AbstractUsernameForgotPasswordChangedCommand";

export default class UsernameForgotPasswordChangedCommand extends AbstractUsernameForgotPasswordChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



