/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelCategoryDialogCommand from "../../../gen/category/commands/AbstractCancelCategoryDialogCommand";

export default class CancelCategoryDialogCommand extends AbstractCancelCategoryDialogCommand {
    execute(data) {
        data.categoryDialog = {
            display: false,
            categoryName: "",
            newCategory: null
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



