/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteCategoryCommand from "../../../gen/category/commands/AbstractCancelDeleteCategoryCommand";

export default class CancelDeleteCategoryCommand extends AbstractCancelDeleteCategoryCommand {
    execute(data) {
        data.deleteCategoryDialog = {
            display: false,
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



