/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelInviteUserCommand from "../../../gen/category/commands/AbstractCancelInviteUserCommand";

export default class CancelInviteUserCommand extends AbstractCancelInviteUserCommand {
    execute(data) {
        data.inviteUserDialog = {
            display: false,
            usernameSearchString: ""
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



