/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCancelCategoryDialogCommand from "../../../gen/category/commands/AbstractCancelCategoryDialogCommand";

export default class CancelCategoryDialogCommand extends AbstractCancelCategoryDialogCommand {
    execute() {
        this.commandData.categoryDialog = {
            display: false,
            categoryName: "",
            newCategory: null
        };
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



