/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCategoryNameChangedCommand from "../../../gen/category/commands/AbstractCategoryNameChangedCommand";

export default class CategoryNameChangedCommand extends AbstractCategoryNameChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



