/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCheckDropAllowedCommand from "../../../gen/category/commands/AbstractCheckDropAllowedCommand";
import {findCategory, isCategoryChildOfParent} from "../utils/CategoryTreeUtils";

export default class CheckDropAllowedCommand extends AbstractCheckDropAllowedCommand {
    execute(data) {
        let dropTarget;
        if (data.categoryId === data.rootCategory.categoryId) {
            dropTarget = data.rootCategory;
        } else {
            dropTarget = findCategory(data.rootCategory.childCategories, data.categoryId);
        }
        data.dropTargetCategoryId = dropTarget.categoryId;
        if (data.movedCategory) {
            if (data.altKey === true) {
                data.dropAllowed =
                    dropTarget.parentCategoryId === data.movedCategory.parentCategoryId
                    && dropTarget.categoryId !== data.movedCategory.categoryId;
            } else {
                data.dropAllowed =
                    data.rootCategory.categoryId !== data.movedCategory.categoryId
                    && dropTarget.categoryId !== data.movedCategory.categoryId
                    && dropTarget.categoryId !== data.movedCategory.parentCategoryId
                    && !isCategoryChildOfParent(data.movedCategory, dropTarget.categoryId);
            }
        } else if (data.movedCardIds) {
            data.dropAllowed = data.selectedCategory.categoryId !== dropTarget.categoryId;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/