/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCollapseTreeItemCommand from "../../../gen/category/commands/AbstractCollapseTreeItemCommand";
import {findCategory, isCategoryChildOfParent} from "../utils/CategoryTreeUtils"

export default class CollapseTreeItemCommand extends AbstractCollapseTreeItemCommand {
    execute(data) {
        let category = findCategory(data.rootCategory.childCategories, data.categoryId);
        category.expanded = false;
        if (data.selectedCategory && isCategoryChildOfParent(category, data.selectedCategory.categoryId)) {
            this.addSelectParentCategoryOutcome(data);
        } else {
            this.addOkOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/