/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractExpandTreeItemCommand from "../../../gen/category/commands/AbstractExpandTreeItemCommand";
import {findCategory} from "../utils/CategoryTreeUtils"

export default class ExpandTreeItemCommand extends AbstractExpandTreeItemCommand {
    execute(data) {
        let category = findCategory(data.rootCategory.childCategories, data.categoryId);
        category.expanded = true;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/

