/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractFilterNonScheduledCardsCommand from "../../../gen/category/commands/AbstractFilterNonScheduledCardsCommand";

export default class FilterNonScheduledCardsCommand extends AbstractFilterNonScheduledCardsCommand {
    execute(data) {
        data.filterNonScheduled = !data.filterNonScheduled;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



