/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetInvitedUsernamesCommand from "../../../gen/category/commands/AbstractGetInvitedUsernamesCommand";

export default class GetInvitedUsernamesCommand extends AbstractGetInvitedUsernamesCommand {

    validateCommandData(data) {
    	//data.categoryId is mandatory String
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



