/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractGetInvitedUsernamesCommand from "../../../gen/category/commands/AbstractGetInvitedUsernamesCommand";

export default class GetInvitedUsernamesCommand extends AbstractGetInvitedUsernamesCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



