/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInviteUserClickCommand from "../../../gen/category/commands/AbstractInviteUserClickCommand";

export default class InviteUserClickCommand extends AbstractInviteUserClickCommand {
    execute(data) {
        data.inviteUserDialog = {
            display: true,
            usernameSearchString: ""
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



