/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractInvitedUsernameChangedCommand from "../../../gen/category/commands/AbstractInvitedUsernameChangedCommand";

export default class InvitedUsernameChangedCommand extends AbstractInvitedUsernameChangedCommand {
    execute() {
    	this.addOkOutcome();
    	if (this.commandData.usernameSearchString.length >= 2) {
    	    this.addSearchOutcome();
        } else {
    	    this.addTooShortOutcome();
        }
    }
}




/******* S.D.G. *******/



