/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractInviteUserCommand from "../../../gen/category/commands/AbstractInviteUserCommand";

export default class InviteUserCommand extends AbstractInviteUserCommand {

    validateCommandData() {
    	//this.commandData.categoryId is mandatory String
    	//this.commandData.invitedUsername is mandatory String
    	return true;
    }

    handleResponse(resolve) {
        this.commandData.displayInviteUser = false;
        this.commandData.usernameSearchString = "";
        this.commandData.invitedUsernames = [];
        this.commandData.usernames = [];
        this.addOkOutcome()
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.error);
    }
}




/******* S.D.G. *******/



