/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractInviteUserClickCommand from "../../../gen/category/commands/AbstractInviteUserClickCommand";

export default class InviteUserClickCommand extends AbstractInviteUserClickCommand {
    execute() {
        this.commandData.inviteUserDialog = {
            display: true,
            usernameSearchString: ""
        };
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



