/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractItemDroppedCommand from "../../../gen/category/commands/AbstractItemDroppedCommand";

export default class ItemDroppedCommand extends AbstractItemDroppedCommand {
    execute(data) {
        if (data.movedCategory) {
            if (data.alt === false) {
                this.addMoveCategoryOutcome(data)
            } else {
                this.addChangeCategoryOrderOutcome(data)
            }
        } else {
            this.addCardOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/



