/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCategoryCommand from "../../../gen/category/commands/AbstractMoveCategoryCommand";

export default class MoveCategoryCommand extends AbstractMoveCategoryCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.selectedCategoryId = data.targetCategoryId;
        data.categoryIdToBeExpanded = data.targetCategoryId;
        data.movedCategory = null;
        data.dropAllowed = null;
        data.dropTargetCategoryId = null;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



