/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPriorityChangedCommand from "../../../gen/category/commands/AbstractPriorityChangedCommand";

export default class PriorityChangedCommand extends AbstractPriorityChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



