/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




import AbstractPriorityChangedCommand from "../../../gen/category/commands/AbstractPriorityChangedCommand";

export default class PriorityChangedCommand extends AbstractPriorityChangedCommand {
    execute() {
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



