/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




import AbstractPriorityChangedCommand from "../../../gen/category/commands/AbstractPriorityChangedCommand";

export default class PriorityChangedCommand extends AbstractPriorityChangedCommand {
    execute() {
        if (this.commandData.priority === this.commandData.actualPriority) {
            this.commandData.priority = null;
        }
    	this.commandData.outcome = this.ok;
    }
}




/******* S.D.G. *******/



