/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import AbstractReloadCategoryTreeCommand from "../../../gen/category/commands/AbstractReloadCategoryTreeCommand";
import {findExpandedCategories, initExpandedState, initSelected} from "../utils/CategoryTreeUtils";

export default class ReloadCategoryTreeCommand extends AbstractReloadCategoryTreeCommand {

    validateCommandData() {
        if (!this.commandData.previousRootCategory && !this.commandData.previousRootCategory.categoryId) {
            return false;
        }
        this.commandData.rootCategoryId = this.commandData.previousRootCategory.categoryId;
        return true;
    }

    handleResponse(resolve) {
        const expandedCategories = [];
        findExpandedCategories(this.commandData.previousRootCategory, expandedCategories);
        if (this.commandData.categoryIdToBeExpanded) {
            expandedCategories.push(this.commandData.categoryIdToBeExpanded);
        }
        initExpandedState(this.commandData.rootCategory, expandedCategories);
        if (this.commandData.selectedCategoryId) {
            this.commandData.selectedCategory = initSelected(this.commandData.rootCategory, this.commandData.selectedCategoryId);
        }
        this.addOkOutcome();
        resolve();
    }

    handleError(resolve, reject) {
        reject(this.commandData.message);
    }
}


/******* S.D.G. *******/



