/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractReloadCategoryTreeCommand from "../../../gen/category/commands/AbstractReloadCategoryTreeCommand";
import {findExpandedCategories, initExpandedState, initSelected} from "../utils/CategoryTreeUtils";

export default class ReloadCategoryTreeCommand extends AbstractReloadCategoryTreeCommand {

    validateCommandData(data) {
        if (!data.previousRootCategory && !data.previousRootCategory.categoryId) {
            return false;
        }
        data.rootCategoryId = data.previousRootCategory.categoryId;
    	return true;
    }

    handleResponse(data, resolve, reject) {
        const expandedCategories = [];
        findExpandedCategories(data.previousRootCategory, expandedCategories);
        if (data.categoryIdToBeExpanded) {
            expandedCategories.push(data.categoryIdToBeExpanded);
        }
        initExpandedState(data.rootCategory, expandedCategories);
        if (data.selectedCategoryId) {
            data.selectedCategory = initSelected(data.rootCategory, data.selectedCategoryId);
        }
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}



/******* S.D.G. *******/



