/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/





import AbstractSearchUsernameCommand from "../../../gen/category/commands/AbstractSearchUsernameCommand";

export default class SearchUsernameCommand extends AbstractSearchUsernameCommand {

    validateCommandData() {
        if (!this.commandData.usernameSearchString || this.commandData.usernameSearchString.length < 2) {
            return false;
        }
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



