/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSearchUsernameCommand from "../../../gen/category/commands/AbstractSearchUsernameCommand";

export default class SearchUsernameCommand extends AbstractSearchUsernameCommand {

    validateCommandData(data) {
        return !(!data.usernameSearchString || data.usernameSearchString.length < 2);

    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



