/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCategoryCommand from "../../../gen/category/commands/AbstractUpdateCategoryCommand";

export default class UpdateCategoryCommand extends AbstractUpdateCategoryCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.categoryDialog = null;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



