/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteBoxAction from "../../../gen/box/actions/AbstractCancelDeleteBoxAction";

export default class CancelDeleteBoxAction extends AbstractCancelDeleteBoxAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



