/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateRootCategoryAction from "../../../gen/box/actions/AbstractCreateRootCategoryAction";

export default class CreateRootCategoryAction extends AbstractCreateRootCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



