/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteBoxClickAction from "../../../gen/box/actions/AbstractDeleteBoxClickAction";

export default class DeleteBoxClickAction extends AbstractDeleteBoxClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



