/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteBoxAction from "../../../gen/box/actions/AbstractDeleteBoxAction";

export default class DeleteBoxAction extends AbstractDeleteBoxAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



