/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDictionaryLookupChangedAction from "../../../gen/box/actions/AbstractDictionaryLookupChangedAction";

export default class DictionaryLookupChangedAction extends AbstractDictionaryLookupChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



