/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDisplayWantedAction from "../../../gen/box/actions/AbstractDisplayWantedAction";

export default class DisplayWantedAction extends AbstractDisplayWantedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



