/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGivenLanguageChangedAction from "../../../gen/box/actions/AbstractGivenLanguageChangedAction";

export default class GivenLanguageChangedAction extends AbstractGivenLanguageChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



