/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadActiveCardsAction from "../../../gen/box/actions/AbstractLoadActiveCardsAction";

export default class LoadActiveCardsAction extends AbstractLoadActiveCardsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



