/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractLoadActiveCardsAction from "../../../gen/box/actions/AbstractLoadActiveCardsAction";

export default class LoadActiveCardsAction extends AbstractLoadActiveCardsAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



