/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMaxCardsPerDayChangedAction from "../../../gen/box/actions/AbstractMaxCardsPerDayChangedAction";

export default class MaxCardsPerDayChangedAction extends AbstractMaxCardsPerDayChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



