/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMaxIntervalChangedAction from "../../../gen/box/actions/AbstractMaxIntervalChangedAction";

export default class MaxIntervalChangedAction extends AbstractMaxIntervalChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



