/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSaveBoxSettingsAction from "../../../gen/box/actions/AbstractSaveBoxSettingsAction";

export default class SaveBoxSettingsAction extends AbstractSaveBoxSettingsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



