/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractScheduleSelectedCardsAction from "../../../gen/box/actions/AbstractScheduleSelectedCardsAction";

export default class ScheduleSelectedCardsAction extends AbstractScheduleSelectedCardsAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



