/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractScoreReinforceCardAction from "../../../gen/box/actions/AbstractScoreReinforceCardAction";

export default class ScoreReinforceCardAction extends AbstractScoreReinforceCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



