/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSortCardOutAction from "../../../gen/box/actions/AbstractSortCardOutAction";

export default class SortCardOutAction extends AbstractSortCardOutAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



