/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractSortSelectedCardsOutAction from "../../../gen/box/actions/AbstractSortSelectedCardsOutAction";

export default class SortSelectedCardsOutAction extends AbstractSortSelectedCardsOutAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



