/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractToggleAllScheduleCardSelectionAction from "../../../gen/box/actions/AbstractToggleAllScheduleCardSelectionAction";

export default class ToggleAllScheduleCardSelectionAction extends AbstractToggleAllScheduleCardSelectionAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



