/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleAllScheduleCardSelectionAction from "../../../gen/box/actions/AbstractToggleAllScheduleCardSelectionAction";

export default class ToggleAllScheduleCardSelectionAction extends AbstractToggleAllScheduleCardSelectionAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



