/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractToggleScheduleCardSelectionAction from "../../../gen/box/actions/AbstractToggleScheduleCardSelectionAction";

export default class ToggleScheduleCardSelectionAction extends AbstractToggleScheduleCardSelectionAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



