/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleScheduleCardSelectionAction from "../../../gen/box/actions/AbstractToggleScheduleCardSelectionAction";

export default class ToggleScheduleCardSelectionAction extends AbstractToggleScheduleCardSelectionAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



