/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractTooManyCardsStatusAction from "../../../gen/box/actions/AbstractTooManyCardsStatusAction";

export default class TooManyCardsStatusAction extends AbstractTooManyCardsStatusAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



