/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractWantedLanguageChangedAction from "../../../gen/box/actions/AbstractWantedLanguageChangedAction";

export default class WantedLanguageChangedAction extends AbstractWantedLanguageChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



