/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelVersionMismatchDialogAction from "../../../gen/common/actions/AbstractCancelVersionMismatchDialogAction";

export default class CancelVersionMismatchDialogAction extends AbstractCancelVersionMismatchDialogAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



