/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelSaveBugDialogAction from "../../../gen/common/actions/AbstractCancelSaveBugDialogAction";

export default class CancelSaveBugDialogAction extends AbstractCancelSaveBugDialogAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



