/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCancelVersionMismatchDialogAction from "../../../gen/common/actions/AbstractCancelVersionMismatchDialogAction";

export default class CancelVersionMismatchDialogAction extends AbstractCancelVersionMismatchDialogAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



