/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractClickToastAction from "../../../gen/common/actions/AbstractClickToastAction";

export default class ClickToastAction extends AbstractClickToastAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



