/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDestroyToastAction from "../../../gen/common/actions/AbstractDestroyToastAction";

export default class DestroyToastAction extends AbstractDestroyToastAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



