/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchErrorDialogAction from "../../../gen/common/actions/AbstractDisplayVersionMismatchErrorDialogAction";

export default class DisplayVersionMismatchErrorDialogAction extends AbstractDisplayVersionMismatchErrorDialogAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



