/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchDialogAction from "../../../gen/common/actions/AbstractDisplayVersionMismatchDialogAction";

export default class DisplayVersionMismatchDialogAction extends AbstractDisplayVersionMismatchDialogAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



