/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDisplayToastAction from "../../../gen/common/actions/AbstractDisplayToastAction";

export default class DisplayToastAction extends AbstractDisplayToastAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



