/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDisplaySaveBugDialogAction from "../../../gen/common/actions/AbstractDisplaySaveBugDialogAction";

export default class DisplaySaveBugDialogAction extends AbstractDisplaySaveBugDialogAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



