/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractHideToastAction from "../../../gen/common/actions/AbstractHideToastAction";

export default class HideToastAction extends AbstractHideToastAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



