/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractHideSaveBugDialogAction from "../../../gen/common/actions/AbstractHideSaveBugDialogAction";

export default class HideSaveBugDialogAction extends AbstractHideSaveBugDialogAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



