/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitAction from "../../../gen/common/actions/AbstractInitAction";

export default class InitAction extends AbstractInitAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



