/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitialLoginAction from "../../../gen/common/actions/AbstractInitialLoginAction";

export default class InitialLoginAction extends AbstractInitialLoginAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



