/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLogoutAction from "../../../gen/common/actions/AbstractLogoutAction";

export default class LogoutAction extends AbstractLogoutAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



