/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRouteAction from "../../../gen/common/actions/AbstractRouteAction";

export default class RouteAction extends AbstractRouteAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



