/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRouteChangedAction from "../../../gen/common/actions/AbstractRouteChangedAction";

export default class RouteChangedAction extends AbstractRouteChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



