/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserAction from "../../../gen/profile/actions/AbstractDeleteUserAction";

export default class DeleteUserAction extends AbstractDeleteUserAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



