/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserClickAction from "../../../gen/profile/actions/AbstractDeleteUserClickAction";

export default class DeleteUserClickAction extends AbstractDeleteUserClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



