/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadUserAction from "../../../gen/profile/actions/AbstractLoadUserAction";

export default class LoadUserAction extends AbstractLoadUserAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



