/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {button, div, h2, input} from "../../../../../../gen/components/ReactHelper";
import {Texts} from "../../../../../app/Texts";
import {
    cancelCategoryDialog,
    categoryNameChanged,
    createCategory,
    updateCategory
} from "../../../../../../gen/category/ActionFunctions";

export function uiElement(attributes) {
    if (attributes.display !== true) {
        return null;
    }
    const disabled =
        !attributes.categoryName ||
        attributes.categoryName.length === 0;
    return div({class: "modal"}, [
        div({class: "modalContent form"}, [
            h2({}, [attributes.newCategory ? Texts.categoryTree.newCategory.title[attributes.language] : Texts.categoryTree.editCategory.title[attributes.language]]),
            div({class: "line"}, [
                input({
                    type: "text",
                    onChange: (event) => categoryNameChanged(event.target.value),
                    autoComplete: "off",
                    value: attributes.categoryName,
                    placeholder: Texts.categoryTree.newCategory.newChildCategory[attributes.language]
                })
            ]),
            button({
                disabled,
                onClick: () => attributes.newCategory ? createCategory() : updateCategory()
            }, [Texts.categoryTree.newCategory.ok[attributes.language]]),
            button({
                onClick: () => cancelCategoryDialog()
            }, [Texts.categoryTree.newCategory.cancel[attributes.language]]),
        ])
    ]);
}


/******* S.D.G. *******/



