/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../../app/Texts";
import {
	cancelCategoryDialog,
	categoryNameChanged,
	createCategory,
	updateCategory
} from "../../../../../../gen/category/ActionFunctions";


export const CategoryDialog = (props) => {
    if (props.display !== true) {
		return null;
	}
	const disabled =
		!props.categoryName ||
		props.categoryName.length === 0;

	return <div className="modal">
		<div className="modalContent form">
			<h2>{props.newCategory ? Texts.categoryTree.newCategory.title[props.language] : Texts.categoryTree.editCategory.title[props.language]}</h2>
			<div className="line">
				<input
					type="text"
					onChange={(event) => categoryNameChanged(event.target.value)}
					autoComplete="off"
					value={props.categoryName}
					placeholder={Texts.categoryTree.newCategory.newChildCategory[props.language]}
				/>
			</div>
			<button
				disabled={disabled}
				onClick={() => props.newCategory ? createCategory() : updateCategory()}
			>
				{Texts.categoryTree.newCategory.ok[props.language]}
			</button>
			<button
				onClick={cancelCategoryDialog}
			>
				{Texts.categoryTree.newCategory.cancel[props.language]}
			</button>
		</div>
	</div>;
}



/******* S.D.G. *******/



