/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../../app/Texts";
import {cancelDeleteCategory, deleteCategory} from "../../../../../../gen/category/ActionFunctions";


export const DeleteCategoryDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{Texts.categoryTree.confirmDelete.title[props.language]}</h2>
				<div className="message">{Texts.categoryTree.confirmDelete.message[props.language]}</div>
				<button
					className="yes danger"
					onClick={deleteCategory}
				>
					{Texts.categoryTree.confirmDelete.ok[props.language]}
				</button>
				<button
					onClick={cancelDeleteCategory}
				>
					{Texts.categoryTree.confirmDelete.cancel[props.language]}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



