/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {button, div, h2} from "../../../../../../gen/components/ReactHelper";
import {Texts} from "../../../../../app/Texts";
import {cancelDeleteCategory, deleteCategory} from "../../../../../../gen/category/ActionFunctions";

export function uiElement(attributes) {
    if (attributes.display === true) {
        return div({class: "modal"}, [
            div({class: "modalContent"}, [
                h2({}, [Texts.categoryTree.confirmDelete.title[attributes.language]]),
                div({class: "message"}, [Texts.categoryTree.confirmDelete.message[attributes.language]]),
                button({
                    class: "yes danger",
                    onClick: () => deleteCategory()
                }, [Texts.categoryTree.confirmDelete.ok[attributes.language]]),
                button({
                    onClick: () => cancelDeleteCategory()}, [Texts.categoryTree.confirmDelete.cancel[attributes.language]])
            ])
        ]);
    }
    return null;
}


/******* S.D.G. *******/



