/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserCommand from "../../../gen/profile/commands/AbstractDeleteUserCommand";

export default class DeleteUserCommand extends AbstractDeleteUserCommand {

    validateCommandData(data) {
    	//data.usernameToBeDeleted is mandatory String
    	return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        data.showDeleteUserDialog = undefined;
    	resolve(data);
    }
    handleError(data, resolve) {
        this.addErrorOutcome(data);
        data.message = data.error;
        data.showDeleteUserDialog = undefined;
        resolve(data);
    }
}



/******* S.D.G. *******/



