/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserCancelCommand from "../../../gen/profile/commands/AbstractDeleteUserCancelCommand";

export default class DeleteUserCancelCommand extends AbstractDeleteUserCancelCommand {
    execute(data) {
        data.showDeleteUserDialog = false;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



