/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserClickCommand from "../../../gen/profile/commands/AbstractDeleteUserClickCommand";

export default class DeleteUserClickCommand extends AbstractDeleteUserClickCommand {
    execute(data) {
        data.showDeleteUserDialog = true;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



