/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import React from "react";

export function uiElement(props) {
	const json = JSON.stringify(props, null, '\t');
	return <pre>{json}</pre>
}



/******* S.D.G. *******/



