/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




module.exports = {
	registerEnabled: function(testId) {
		fail("registerEnabled not implemented");
	}
}



/******* S.D.G. *******/


