/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




const {registerDisabled} = require("./Utils");


module.exports = {
	registerDisabled: registerDisabled
}



/******* S.D.G. *******/


