/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




const {registerEnabled} = require("./Utils");


module.exports = {
	registerEnabled: registerEnabled
}


/******* S.D.G. *******/


