/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




module.exports = {
	registerDisabled: function(testId) {
		fail("registerDisabled not implemented");
	}
}



/******* S.D.G. *******/


