/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import React from "react";
import AppUtils from "../../app/AppUtils";
import {destroyToast} from "../../../gen/common/ActionFunctions";

export function uiElement(props) {
    const text = AppUtils.getMessageText(props, props.language);
    return <div
        className={`toastWrapper ${props.visible === false ? "fadeOut" : ""}`}
        onClick={() => destroyToast(props.id)}
    >
        <div className={`toast ${props.type}`}>{text}</div>
    </div>
}


/******* S.D.G. *******/



