/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {Texts} from "../../app/Texts";
import {cancelVersionMismatchDialog} from "../../../gen/common/ActionFunctions";
import React from "react";

export function uiElement(props) {
    if (props.display === true) {
        return <div className="modal">
            <div className="modalContent">
                <h2>{Texts.container.versionMismatch[props.language]}</h2>
                <div className="message">{Texts.container.versionMismatchMessage[props.language]}</div>
                <button
                    className="yes"
                    onClick={() => window.location.reload(true)}
                >
                    Texts.container.yes[props.language]
                </button>
                <button
                    onClick={() => cancelVersionMismatchDialog()}
                >
                    Texts.container.no[props.language]
                </button>
            </div>
        </div>
    }
    return null;
}

/******* S.D.G. *******/



