/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetRoleCommand from "../../../gen/login/commands/AbstractGetRoleCommand";
import * as AppUtils from "../../app/AppUtils";

export default class GetRoleCommand extends AbstractGetRoleCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        data.hash = "#dashboard";
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
        if (AppUtils.isUnauthorized(data.error)) {
            this.addUnauthorizedOutcome(data);
            data.message = data.error;
            resolve(data);
        } else {
            reject(data.error);
        }
    }
}




/******* S.D.G. *******/
