/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractPasswordChangedCommand from "../../../gen/login/commands/AbstractPasswordChangedCommand";

export default class PasswordChangedCommand extends AbstractPasswordChangedCommand {
    execute() {
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



