/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPasswordChangedCommand from "../../../gen/login/commands/AbstractPasswordChangedCommand";

export default class PasswordChangedCommand extends AbstractPasswordChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



