/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleSaveInLocalStorageCommand from "../../../gen/login/commands/AbstractToggleSaveInLocalStorageCommand";

export default class ToggleSaveInLocalStorageCommand extends AbstractToggleSaveInLocalStorageCommand {
    execute(data) {
        data.saveInLocalStorage = !data.saveInLocalStorage;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



