/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import * as AppState from "../../gen/ace/AppState";
import * as Utils from "../../gen/ace/Utils";
import * as App from "../../gen/app/App";

import EventListenerRegistrationCategory from "../../gen/category/EventListenerRegistration";
import EventListenerRegistrationCard from "../../gen/card/EventListenerRegistration";
import EventListenerRegistrationBox from "../../gen/box/EventListenerRegistration";
import EventListenerRegistrationCommon from "../../gen/common/EventListenerRegistration";
import EventListenerRegistrationProfile from "../../gen/profile/EventListenerRegistration";
import EventListenerRegistrationRegistration from "../../gen/registration/EventListenerRegistration";
import EventListenerRegistrationLogin from "../../gen/login/EventListenerRegistration";
import EventListenerRegistrationPassword from "../../gen/password/EventListenerRegistration";
import {
    displaySaveBugDialog,
    displayToast,
    displayVersionMismatchDialog,
    displayVersionMismatchErrorDialog,
    init,
    routeChanged,
} from "../../gen/common/ActionFunctions";
import CryptoJS from "crypto-js";
import {dumpTimeline} from "../../gen/ace/Timeline";
import {Texts} from "./Texts";
import {RootContainer, setRootContainerState} from "../components/RootContainer";
import React from "react";
import ReactDOM from "react-dom";

export function initEventListeners() {
    EventListenerRegistrationCategory.init();
    EventListenerRegistrationCard.init();
    EventListenerRegistrationBox.init();
    EventListenerRegistrationCommon.init();
    EventListenerRegistrationProfile.init();
    EventListenerRegistrationRegistration.init();
    EventListenerRegistrationLogin.init();
    EventListenerRegistrationPassword.init();
}

export function startApp() {
    window.onhashchange = () => {
        routeChanged();
        window.scrollTo(0, 0);
    };
    Utils.loadSettings().then(() => {
        init(location.hash, localStorage.getItem("username"), localStorage.getItem("password"));
    });
    setInterval(() => {
        const currentVersion = Utils.settings.clientVersion;
        loadActualClientVersion().then((actualClientVersion) => {
            if (actualClientVersion !== currentVersion) {
                displayVersionMismatchDialog();
            }
        });
    }, 180 * 1000);
}

function loadActualClientVersion() {
    return httpRequest("GET", "settings.json").then((settings) => {
        return settings.clientVersion;
    })
}

export function startReplay() {
    window.onhashchange = () => {
    };
}

export function createInitialAppState() {
    const initialAppState = {};
    AppState.setInitialAppState(initialAppState);
}

function createHeaders(authorize) {
    const headers = new Headers();
    headers.append("Content-Type", "application/json");
    headers.append("Accept", "application/json");
    if (authorize === true) {
        let authorization = basicAuth();
        if (authorization !== undefined) {
            headers.append("Authorization", authorization);
        }
    }
    return headers;
}

function addUuidToUrl(url, uuid) {
    if (uuid) {
        if (url.indexOf("?") < 0) {
            url += "?uuid=" + uuid;
        } else {
            url += "&uuid=" + uuid;
        }
    }
    return url;
}

function httpRequest(methodType, url, uuid, authorize, data) {
    return new Promise((resolve, reject) => {
        const options = {
            method: methodType,
            headers: createHeaders(authorize),
            mode: 'cors',
            cache: 'no-cache'
        };
        if (data && methodType !== "GET") {
            options.body = JSON.stringify(data);
        }
        url = addUuidToUrl(url, uuid);
        const request = new Request(url, options);

        fetch(request).then(function (response) {
            response.text().then((text) => {
                if (response.status >= 300) {
                    const error = createError(text, response.statusText, response.status);
                    reject(error);
                } else {
                    let data = {};
                    if (text.length > 0) {
                        data = JSON.parse(text);
                    }
                    resolve(data);
                }
            });
        }).catch(function (error) {
            reject(createError(error, error));
        });
    });
}

export function httpGet(url, uuid, authorize) {
    return httpRequest("GET", url, uuid, authorize, null);
}

export function httpPost(url, uuid, authorize, data) {
    return httpRequest("POST", url, uuid, authorize, data);
}

export function httpPut(url, uuid, authorize, data) {
    return httpRequest("PUT", url, uuid, authorize, data);
}

export function httpDelete(url, uuid, authorize, data) {
    return httpRequest("DELETE", url, uuid, authorize, data);
}

function basicAuth() {
    const username = AppState.get_rootContainer_loggedInUser_username();
    const password = AppState.get_rootContainer_loggedInUser_password();
    if (username !== undefined && password !== undefined) {
        const wordArray = CryptoJS.enc.Utf8.parse(username + ':' + password);
        const hash = CryptoJS.enc.Base64.stringify(wordArray);
        return "anfelisaBasic " + hash;
    }
    return undefined;
}

export function createUUID() {
    let d = new Date().getTime();
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
        let r = (d + Math.random() * 16) % 16 | 0;
        d = Math.floor(d / 16);
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
}

export function displayUnexpectedError(error) {
    console.error("unexpected error", error);
    const currentVersion = Utils.settings.clientVersion;
    App.dumpAppState();
    dumpTimeline();
    loadActualClientVersion().then((actualClientVersion) => {
        if (actualClientVersion !== currentVersion) {
            displayVersionMismatchErrorDialog();
        } else {
            if (typeof error !== "object") {
                displayToast(createError("unknownError", error));
            } else {
                displayToast(error);
            }
            displaySaveBugDialog();
        }
    });
}

export function createInfoMessage(textKey) {
    return {
        textKey,
        type: "info"
    }
}

export function createError(textKey, text, code) {
    return {
        code,
        text,
        textKey: code && code === 401 ? "loginFailed" : textKey,
        type: "error"
    }
}

export function isUnauthorized(message) {
    return (message && message.code && message.code === 401);
}


export function getMessageText(message, language) {
    if (message && language) {
        if (message.type === "error" && Texts.messages.unknownError && Texts.messages.unknownError[language]) {
            if (message.text && typeof message.text !== "object") {
                return Texts.messages.unknownError[language].replace("{0}", message.text);
            }
            if (message.code && typeof message.code !== "object") {
                return Texts.messages.unknownError[language].replace("{0}", message.code);
            }
            if (message.textKey && typeof message.textKey !== "object") {
                return Texts.messages.unknownError[language].replace("{0}", message.textKey);
            }
        }
        if (message.textKey && Texts.messages[message.textKey] && Texts.messages[message.textKey][language]) {
            return Texts.messages[message.textKey][language];
        }
    }
    if (language) {
        return Texts.messages.unknown[language];
    }
    return "unknown message";
}

export function deepCopy(object) {
    return JSON.parse(JSON.stringify(object));
}

let container;

export function stateUpdated() {
    const appState = AppState.getAppState();
    setRootContainerState(appState.rootContainer);
}

export function renderApp() {
    container = <RootContainer {...AppState.getAppState()} />;
    container = ReactDOM.render(
        container,
        document.getElementById('root')
    );
}


/******* S.D.G. *******/



