/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




module.exports = {
	saveEnabled: async function(driver, testId) {
		fail("saveEnabled not implemented");
	},
	givenLanguageEnabled: async function(driver, testId) {
		fail("givenLanguageEnabled not implemented");
	},
	wantedLanguageEnabled: async function(driver, testId) {
		fail("wantedLanguageEnabled not implemented");
	}
}



/******* S.D.G. *******/


