/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/


const {saveDisabled, givenLanguageEnabled, wantedLanguageEnabled} = require("./Utils");


module.exports = {
	saveDisabled: saveDisabled,
	givenLanguageEnabled: givenLanguageEnabled,
	wantedLanguageEnabled: wantedLanguageEnabled,
}


/******* S.D.G. *******/


