/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/


const {saveDisabled} = require("./Utils");


module.exports = {
	saveDisabled: saveDisabled
}



/******* S.D.G. *******/


