/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/


const {saveEnabled, givenLanguageEnabled, wantedLanguageEnabled} = require("./Utils");


module.exports = {
	saveEnabled: saveEnabled,
	givenLanguageEnabled: givenLanguageEnabled,
	wantedLanguageEnabled: wantedLanguageEnabled
}



/******* S.D.G. *******/


