/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";


export const UserListItem = (props) => {
	const json = JSON.stringify(props, null, '\t');
	return <div>
		<div>{props.userId}</div>
		<div>{props.username}</div>
		<div>{props.password}</div>
		<div>{props.email}</div>
		<div>{props.role}</div>
		<div>{props.emailConfirmed}</div>
		<pre>{json}</pre>
	</div> 
}



/******* S.D.G. *******/



