/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCheckUsernameAction from "../../../gen/registration/actions/AbstractCheckUsernameAction";

export default class CheckUsernameAction extends AbstractCheckUsernameAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



