/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractConfirmEmailAction from "../../../gen/registration/actions/AbstractConfirmEmailAction";

export default class ConfirmEmailAction extends AbstractConfirmEmailAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



