/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEmailChangedAction from "../../../gen/registration/actions/AbstractEmailChangedAction";

export default class EmailChangedAction extends AbstractEmailChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



