/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractLoginAction from "../../../gen/registration/actions/AbstractLoginAction";

export default class LoginAction extends AbstractLoginAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



