/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractPasswordRepetitionChangedAction from "../../../gen/registration/actions/AbstractPasswordRepetitionChangedAction";

export default class PasswordRepetitionChangedAction extends AbstractPasswordRepetitionChangedAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



