/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRegisterUserAction from "../../../gen/registration/actions/AbstractRegisterUserAction";

export default class RegisterUserAction extends AbstractRegisterUserAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



