/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCancelInviteUserAction from "../../../gen/category/actions/AbstractCancelInviteUserAction";

export default class CancelInviteUserAction extends AbstractCancelInviteUserAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



