/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelInviteUserAction from "../../../gen/category/actions/AbstractCancelInviteUserAction";

export default class CancelInviteUserAction extends AbstractCancelInviteUserAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



