/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelCategoryDialogAction from "../../../gen/category/actions/AbstractCancelCategoryDialogAction";

export default class CancelCategoryDialogAction extends AbstractCancelCategoryDialogAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



