/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCancelCategoryDialogAction from "../../../gen/category/actions/AbstractCancelCategoryDialogAction";

export default class CancelCategoryDialogAction extends AbstractCancelCategoryDialogAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



