/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteCategoryAction from "../../../gen/category/actions/AbstractCancelDeleteCategoryAction";

export default class CancelDeleteCategoryAction extends AbstractCancelDeleteCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



