/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCategoryNameChangedAction from "../../../gen/category/actions/AbstractCategoryNameChangedAction";

export default class CategoryNameChangedAction extends AbstractCategoryNameChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



