/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractChangeOrderCategoryAction from "../../../gen/category/actions/AbstractChangeOrderCategoryAction";

export default class ChangeOrderCategoryAction extends AbstractChangeOrderCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



