/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCheckDropAllowedAction from "../../../gen/category/actions/AbstractCheckDropAllowedAction";

export default class CheckDropAllowedAction extends AbstractCheckDropAllowedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



