/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCollapseTreeItemAction from "../../../gen/category/actions/AbstractCollapseTreeItemAction";

export default class CollapseTreeItemAction extends AbstractCollapseTreeItemAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



