/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateReverseBoxAction from "../../../gen/category/actions/AbstractCreateReverseBoxAction";

export default class CreateReverseBoxAction extends AbstractCreateReverseBoxAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



