/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCategoryAction from "../../../gen/category/actions/AbstractCreateCategoryAction";

export default class CreateCategoryAction extends AbstractCreateCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



