/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCreateReverseBoxAction from "../../../gen/category/actions/AbstractCreateReverseBoxAction";

export default class CreateReverseBoxAction extends AbstractCreateReverseBoxAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



