/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCategoryClickAction from "../../../gen/category/actions/AbstractDeleteCategoryClickAction";

export default class DeleteCategoryClickAction extends AbstractDeleteCategoryClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



