/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCategoryAction from "../../../gen/category/actions/AbstractDeleteCategoryAction";

export default class DeleteCategoryAction extends AbstractDeleteCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



