/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditCategoryClickAction from "../../../gen/category/actions/AbstractEditCategoryClickAction";

export default class EditCategoryClickAction extends AbstractEditCategoryClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



