/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractExpandTreeItemAction from "../../../gen/category/actions/AbstractExpandTreeItemAction";

export default class ExpandTreeItemAction extends AbstractExpandTreeItemAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



