/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




import AbstractFilterNonScheduledCardsAction from "../../../gen/category/actions/AbstractFilterNonScheduledCardsAction";

export default class FilterNonScheduledCardsAction extends AbstractFilterNonScheduledCardsAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



