/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInviteUserClickAction from "../../../gen/category/actions/AbstractInviteUserClickAction";

export default class InviteUserClickAction extends AbstractInviteUserClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



