/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractInvitedUsernameChangedAction from "../../../gen/category/actions/AbstractInvitedUsernameChangedAction";

export default class InvitedUsernameChangedAction extends AbstractInvitedUsernameChangedAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



