/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInvitedUsernameChangedAction from "../../../gen/category/actions/AbstractInvitedUsernameChangedAction";

export default class InvitedUsernameChangedAction extends AbstractInvitedUsernameChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



