/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInviteUserAction from "../../../gen/category/actions/AbstractInviteUserAction";

export default class InviteUserAction extends AbstractInviteUserAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



