/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCategoryStartedAction from "../../../gen/category/actions/AbstractMoveCategoryStartedAction";

export default class MoveCategoryStartedAction extends AbstractMoveCategoryStartedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



