/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCategoryAction from "../../../gen/category/actions/AbstractMoveCategoryAction";

export default class MoveCategoryAction extends AbstractMoveCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



