/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractNewCategoryClickAction from "../../../gen/category/actions/AbstractNewCategoryClickAction";

export default class NewCategoryClickAction extends AbstractNewCategoryClickAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



