/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPriorityChangedAction from "../../../gen/category/actions/AbstractPriorityChangedAction";

export default class PriorityChangedAction extends AbstractPriorityChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



