/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractReloadCategoryTreeAction from "../../../gen/category/actions/AbstractReloadCategoryTreeAction";

export default class ReloadCategoryTreeAction extends AbstractReloadCategoryTreeAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



