/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSearchUsernameAction from "../../../gen/category/actions/AbstractSearchUsernameAction";

export default class SearchUsernameAction extends AbstractSearchUsernameAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



