/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractSearchUsernameAction from "../../../gen/category/actions/AbstractSearchUsernameAction";

export default class SearchUsernameAction extends AbstractSearchUsernameAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



