/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSelectTreeItemAction from "../../../gen/category/actions/AbstractSelectTreeItemAction";

export default class SelectTreeItemAction extends AbstractSelectTreeItemAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



