/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCategoryAction from "../../../gen/category/actions/AbstractUpdateCategoryAction";

export default class UpdateCategoryAction extends AbstractUpdateCategoryAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



