/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/
import {Texts} from "../../../../es6/src/app/Texts";

export function registerDisabled() {
	cy.contains(Texts.registration.register["de"]).should('be.disabled')
}

/******* S.D.G. *******/


