/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




export function loginDataWasNotSetInLocalStorage(testId) {
	expect(localStorage.getItem("username"), "username").to.eql(null);
	expect(localStorage.getItem("password"), "password").to.eql(null);
}



/******* S.D.G. *******/


