import {Texts} from "../../../../es6/src/app/Texts";

/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




export function registerDisabled() {
	cy.contains(Texts.registration.register["de"]).should('be.disabled')
}



/******* S.D.G. *******/


