/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {Texts} from "../app/Texts";


import {
	a,
	div,
	h1,
	loggedInUser,
	mainView,
	message,
	p,
	saveBugDialog,
	spinner,
	versionMismatchDialog,
	versionMismatchErrorDialog
} from "../../gen/components/ReactHelper";
import Utils from "../../gen/ace/Utils";
import {route} from "../../gen/common/ActionFunctions";

export function uiElement(attributes) {
	return div({}, [
		loggedInUser({ ...attributes.mainView, language: attributes.language }),
		spinner({ ...attributes.mainView, language: attributes.language }),
		saveBugDialog({ ...attributes.mainView, language: attributes.language }),
		versionMismatchDialog({ ...attributes.mainView, language: attributes.language }),
		versionMismatchErrorDialog({ ...attributes.mainView, language: attributes.language }),
		//message({ ...attributes.mainView, language: attributes.language }),
		mainView({ language: attributes.language }),
		div({class: `footer ${attributes.loggedInUser === undefined ? "fixed" : ""}`}, [
			div({class: "footerContent"}, [
					h1({}, [Texts.container.about[attributes.language]]),
					p({}, ["Annette Pohl · St.-Josef-Str. 20 · 56068 Koblenz"]),
					p({}, [
						"0261 1393793 · ",
						a({href: "mailto:info@anfelisa.de"}, ["info@anfelisa.de"])
					]),
					p({}, [
						`${Texts.container.version[attributes.language]} ${Utils && Utils.settings ? Utils.settings.clientVersion : ""}`
					]),
					p({}, [
						a({onClick: () => Utils.saveTimeline("save timeline", attributes.mainView && attributes.mainView.loggedInUser ? attributes.mainView.loggedInUser.username : "anonymous")}, [Texts.login.saveTimeline[attributes.language]])
					]),
					p({}, [
						a({onClick: () => route("#privacypolicy")}, [Texts.login.privacyPolicy[attributes.language]])
					]),
				]
			)
		])
	]);
}



/******* S.D.G. *******/



