/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetRoleAction from "../../../gen/login/actions/AbstractGetRoleAction";

export default class GetRoleAction extends AbstractGetRoleAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



