/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoginAction from "../../../gen/login/actions/AbstractLoginAction";

export default class LoginAction extends AbstractLoginAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



