/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractPasswordChangedAction from "../../../gen/login/actions/AbstractPasswordChangedAction";

export default class PasswordChangedAction extends AbstractPasswordChangedAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



