/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleSaveInLocalStorageAction from "../../../gen/login/actions/AbstractToggleSaveInLocalStorageAction";

export default class ToggleSaveInLocalStorageAction extends AbstractToggleSaveInLocalStorageAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



