/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUsernameChangedAction from "../../../gen/login/actions/AbstractUsernameChangedAction";

export default class UsernameChangedAction extends AbstractUsernameChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



