/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCheckUsernameCommand from "../../../gen/registration/commands/AbstractCheckUsernameCommand";

export default class CheckUsernameCommand extends AbstractCheckUsernameCommand {

    validateCommandData(data) {
        if (data.username.length === 0) {
            this.addEmptyOutcome(data);
            data.available = null;
            return false;
        }
    	return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



