/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractConfirmEmailCommand from "../../../gen/registration/commands/AbstractConfirmEmailCommand";
import * as AppUtils from "../../app/AppUtils";

export default class ConfirmEmailCommand extends AbstractConfirmEmailCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.hash = "#";
        data.message = AppUtils.createInfoMessage("emailConfirmed");
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



