/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoginCommand from "../../../gen/registration/commands/AbstractLoginCommand";

export default class LoginCommand extends AbstractLoginCommand {
    execute(data) {
        data.loggedInUser = {
            username: data.username,
            password: data.password
        };
        data.username = undefined;
        data.password = undefined;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



