/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractLoginCommand from "../../../gen/registration/commands/AbstractLoginCommand";

export default class LoginCommand extends AbstractLoginCommand {
    execute() {
        this.commandData.loggedInUser = {
            username: this.commandData.username,
            password: this.commandData.password
        };
        this.commandData.username = undefined;
        this.commandData.password = undefined;
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



