/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPasswordChangedCommand from "../../../gen/registration/commands/AbstractPasswordChangedCommand";

export default class PasswordChangedCommand extends AbstractPasswordChangedCommand {
    execute(data) {
        data.passwordMismatch = data.password !== data.passwordRepetition;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



