/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractPasswordRepetitionChangedCommand from "../../../gen/registration/commands/AbstractPasswordRepetitionChangedCommand";

export default class PasswordRepetitionChangedCommand extends AbstractPasswordRepetitionChangedCommand {
    execute() {
        this.commandData.passwordMismatch = this.commandData.password !== this.commandData.passwordRepetition;
        this.addOkOutcome();
    }
}




/******* S.D.G. *******/



