/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUsernameChangedCommand from "../../../gen/registration/commands/AbstractUsernameChangedCommand";

export default class UsernameChangedCommand extends AbstractUsernameChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



