/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {a, button, div} from "../../../gen/components/ReactHelper";
import {logout, route} from "../../../gen/common/ActionFunctions";
import {Texts} from "../../app/Texts";

export function uiElement(attributes) {
    console.log("logged in user", attributes);
    if (attributes.role) {
        return div({class: "logout"}, [
            a({onClick: () => route("#profile")}, [attributes.username]),
            button({onClick: () => logout()}, [Texts.logout.signout[attributes.language]])
        ])
    }
    return null;
}


/******* S.D.G. *******/



