/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {logout, route} from "../../../gen/common/ActionFunctions";
import {Texts} from "../../app/Texts";
import React from "react";

export function uiElement(props) {
    if (props.role) {
        return <div className="logout">
            <a onClick={() => route("#profile")}>{props.username}</a>
            <button id="logout" onClick={logout}>{Texts.logout.signout[props.language]}</button>
        </div>
    }
    return null;
}


/******* S.D.G. *******/



