/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import {  privacyPolicyView, loginView, registrationView, forgotPasswordView, resetPasswordView, dashboardView, boxSettingsView, allActiveCardsView, profileView, userListView, queryCardView, authorView} from "../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	if (attributes.isPrivacyPolicyView === true) {
		return privacyPolicyView(attributes, []);
	}
	if (attributes.isLoginView === true) {
		return loginView(attributes, []);
	}
	if (attributes.isRegistrationView === true) {
		return registrationView(attributes, []);
	}
	if (attributes.isForgotPasswordView === true) {
		return forgotPasswordView(attributes, []);
	}
	if (attributes.isResetPasswordView === true) {
		return resetPasswordView(attributes, []);
	}
	if (attributes.isDashboardView === true) {
		return dashboardView(attributes, []);
	}
	if (attributes.isBoxSettingsView === true) {
		return boxSettingsView(attributes, []);
	}
	if (attributes.isAllActiveCardsView === true) {
		return allActiveCardsView(attributes, []);
	}
	if (attributes.isProfileView === true) {
		return profileView(attributes, []);
	}
	if (attributes.isUserListView === true) {
		return userListView(attributes, []);
	}
	if (attributes.isQueryCardView === true) {
		return queryCardView(attributes, []);
	}
	if (attributes.isAuthorView === true) {
		return authorView(attributes, []);
	}
	return null;
}



/******* S.D.G. *******/



