/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { PrivacyPolicyView } from "./mainView/PrivacyPolicyView";
import { LoginView } from "./mainView/LoginView";
import { RegistrationView } from "./mainView/RegistrationView";
import { ForgotPasswordView } from "./mainView/ForgotPasswordView";
import { ResetPasswordView } from "./mainView/ResetPasswordView";
import { DashboardView } from "./mainView/DashboardView";
import { BoxSettingsView } from "./mainView/BoxSettingsView";
import { AllActiveCardsView } from "./mainView/AllActiveCardsView";
import { ProfileView } from "./mainView/ProfileView";
import { UserListView } from "./mainView/UserListView";
import { QueryCardView } from "./mainView/QueryCardView";
import { AuthorView } from "./mainView/AuthorView";

export const MainView = (props) => {
	if (props.isPrivacyPolicyView === true) {
		return <PrivacyPolicyView {...props}/>;
	}
	if (props.isLoginView === true) {
		return <LoginView {...props}/>;
	}
	if (props.isRegistrationView === true) {
		return <RegistrationView {...props}/>;
	}
	if (props.isForgotPasswordView === true) {
		return <ForgotPasswordView {...props}/>;
	}
	if (props.isResetPasswordView === true) {
		return <ResetPasswordView {...props}/>;
	}
	if (props.isDashboardView === true) {
		return <DashboardView {...props}/>;
	}
	if (props.isBoxSettingsView === true) {
		return <BoxSettingsView {...props}/>;
	}
	if (props.isAllActiveCardsView === true) {
		return <AllActiveCardsView {...props}/>;
	}
	if (props.isProfileView === true) {
		return <ProfileView {...props}/>;
	}
	if (props.isUserListView === true) {
		return <UserListView {...props}/>;
	}
	if (props.isQueryCardView === true) {
		return <QueryCardView {...props}/>;
	}
	if (props.isAuthorView === true) {
		return <AuthorView {...props}/>;
	}
	return null;
}



/******* S.D.G. *******/



