/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div, h1, label, input, table, tbody, ul, li, tr, td } from "../../../gen/components/ReactHelper";
import AppUtils from "../../app/AppUtils";

export function uiElement(attributes) {
	const text = AppUtils.getMessageText(attributes, attributes.language);
	return div({class:`toastWrapper ${attributes.visible === false ? "fadeOut": ""}`}, [
		div({class:`toast ${attributes.type}`}, [text])
	])
}


/******* S.D.G. *******/



