/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {button, div, h2} from "../../../gen/components/ReactHelper";
import {Texts} from "../../app/Texts";
import {callSaveBug, cancelSaveBugDialog} from "../../../gen/common/ActionFunctions";

export function uiElement(attributes) {
    if (attributes.display === true) {
        return div({class: "modal"}, [
            div({class: "modalContent"}, [
                h2({}, [Texts.container.unexpectedBug[attributes.language]]),
                div({class: "message"}, [Texts.container.unexpectedBugMessage[attributes.language]]),
                button({class: "yes", onClick: () => callSaveBug()}, [Texts.container.yes[attributes.language]]),
                button({onClick: () => cancelSaveBugDialog()}, [Texts.container.no[attributes.language]])
            ])
        ]);
    }
    return null;
}


/******* S.D.G. *******/



