/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";


export const Spinner = (props) => {
	if (props.display === true) {
		return <div className="spinner">
			<i className="fas fa-cog fa-spin"/>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



