/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";


export const VersionMismatchErrorDialog = (props) => {
	const json = JSON.stringify(props, null, '\t');
	return <div>
		<div>{props.display}</div>
		<pre>{json}</pre>
	</div> 
}



/******* S.D.G. *******/



