/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {button, div, h2} from "../../../gen/components/ReactHelper";
import {Texts} from "../../app/Texts";

export function uiElement(attributes) {
    if (attributes.display === true) {
        return div({class: "modal"}, [
            div({class: "modalContent danger"}, [
                h2({}, [Texts.container.versionMismatchError[attributes.language]]),
                div({class: "message"}, [Texts.container.versionMismatchErrorMessage[attributes.language]]),
                button({
                    class: "yes",
                    onClick: () => window.location.reload(true)
                }, [Texts.container.yes[attributes.language]])
            ])
        ]);
    }
    return null;
}


/******* S.D.G. *******/



