/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../app/Texts";
import {cancelVersionMismatchDialog} from "../../../gen/common/ActionFunctions";


export const VersionMismatchDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{Texts.container.versionMismatch[props.language]}</h2>
				<div className="message">{Texts.container.versionMismatchMessage[props.language]}</div>
				<button
					className="yes"
					onClick={() => window.location.reload(true)}
				>
					Texts.container.yes[props.language]
				</button>
				<button
					onClick={() => cancelVersionMismatchDialog()}
				>
					Texts.container.no[props.language]
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



