/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import React from "react";
import {Texts} from "../../app/Texts";

export function uiElement(props) {
    if (props.display === true) {
        return <div className="modal">
            <div className="modalContent danger">
                <h2>{Texts.container.versionMismatchError[props.language]}</h2>
                <div className="message">{Texts.container.versionMismatchErrorMessage[props.language]}</div>
                <button
                    className="yes"
                    onClick={() => window.location.reload(true)}
                >
                    Texts.container.yes[props.language]
                </button>
            </div>
        </div>
    }
    return null;
}


/******* S.D.G. *******/



