/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {
    button,
    cardDuplicatesItem,
    cardListItem,
    deleteCard,
    div,
    h1,
    i,
    iframe,
    input,
    newCard,
    table,
    tbody,
    td,
    th,
    thead,
    tr
} from "../../../../../gen/components/ReactHelper";
import {Texts} from "../../../../app/Texts";
import {
    filterCards,
    scheduleSelectedCards,
    sortSelectedCardsOut,
    toggleAllScheduleCardSelection,
    toggleInputOrder
} from "../../../../../gen/card/ActionFunctions";
import React from "react";

export function uiElement(attributes) {
    if (!attributes.categoryTree || !attributes.cardList) {
        return null;
    }
    const editable = attributes.categoryTree.rootCategory.editable;
    const cardItems = attributes.cardList.filter((card) => (card.given.indexOf(attributes.filter) >= 0 || card.wanted.indexOf(attributes.filter) >= 0)).map((card) => {
        return cardListItem({
            ...card,
            id: card.cardId,
            selectedCardIds: attributes.selectedCardIds,
            dragTargetCardId: attributes.dragTargetCardId,
            language: attributes.language,
            naturalInputOrder: attributes.naturalInputOrder,
            editable,
            editedCard: attributes.editedCard,
            dictionaryLookup: attributes.categoryTree.selectedCategory.dictionaryLookup,
            givenLanguage: attributes.categoryTree.selectedCategory.givenLanguage,
            wantedLanguage: attributes.categoryTree.selectedCategory.wantedLanguage,
        })
    });
    const duplicateCards = attributes.cardDuplicates.map((card) => {
        return cardDuplicatesItem({
            ...card,
            id: card.cardId,
            naturalInputOrder: attributes.naturalInputOrder,
        })
    });

    if (editable) {
        cardItems.push(
            newCard({
                id: "new",
                dictionaryLookup: attributes.categoryTree.selectedCategory.dictionaryLookup,
                givenLanguage: attributes.categoryTree.selectedCategory.givenLanguage,
                wantedLanguage: attributes.categoryTree.selectedCategory.wantedLanguage,
                naturalInputOrder: attributes.naturalInputOrder,
                language: attributes.language
            })
        );
    }

    const dictionary = () => {
        const setFocus = () => {
            document.getElementById(attributes.naturalInputOrder === true ? "wanted" : "given").focus();
        }

        const value = attributes.dictionaryValue;

        if (!value || value.length === 0) {
            return div({class: "iframePlaceholder"}, []);
        }

        const languageMap = {
            "de": "deutsch",
            "fr": "franzoesisch",
            "en": "englisch"
        };
        const sourceLanguage = attributes.naturalInputOrder === true ? attributes.givenLanguage : attributes.wantedLanguage;
        const targetLanguage = attributes.naturalInputOrder === true ? attributes.wantedLanguage : attributes.givenLanguage;

        const src = `https://www.linguee.de/${languageMap[sourceLanguage]}-${languageMap[targetLanguage]}/search?source=${languageMap[sourceLanguage]}&query=${value}`;
        return div({class: "dictionaryWrapper"}, [
            iframe({
                src,
                frameBorder: 0,
                onLoad: setFocus
            })
        ]);
    }


    return div({}, [
        h1({}, [
            attributes.categoryTree.selectedCategory.categoryName,
            attributes.reverse === true ? i({class: "fas fa-arrows-alt-h"}) : null,
        ]),
        deleteCard({...attributes.deleteCard, language: attributes.language}),
        attributes.deleteCard.confirmDelete === true && editable ? div() : null,
        table({class: "cardTable"}, [
            thead({}, [
                tr({class: "notPrinted"}, [
                    th({colSpan: 4}, [
                        button({
                            title: Texts.cardList.toggleInputOrder[attributes.language],
                            onClick: () => toggleInputOrder()
                        }, [
                            i({class: "fas fa-arrows-alt-h"})
                        ]),
                        input({
                            type: "text",
                            onChange: (event) => filterCards(event.target.value),
                            autoComplete: "off",
                            value: attributes.filter,
                            placeholder: Texts.cardList.filterCards[attributes.language]
                        }),
                    ]),
                ]),
                tr({class: "notPrinted"}, [
                    th({}, [
                        input({
                            type: "checkbox",
                            onChange: () => toggleAllScheduleCardSelection(),
                            checked: attributes.cardList.length > 0 && attributes.selectedCardIds.length === attributes.cardList.length,
                        }),
                    ]),
                    th({colSpan: 4}, [
                        button({
                            disabled: attributes.selectedCardIds.length === 0,
                            onClick: () => scheduleSelectedCards()
                        }, [
                            Texts.cardList.scheduleSelectedCards[attributes.language]
                        ]),
                        button({
                            disabled: attributes.selectedCardIds.length === 0,
                            onClick: () => sortSelectedCardsOut()
                        }, [
                            Texts.cardList.sortSelectedCardsOut[attributes.language]
                        ]),
                    ]),
                ]),
            ]),
            tbody({}, [
                ...cardItems,
                duplicateCards.length > 0 && editable ? tr({}, [
                    td(),
                    td({colSpan: 5}, [Texts.cardList.duplicateCards[attributes.language]]),
                ]) : null,
                ...duplicateCards
            ]),
        ]),
        dictionary()

    ]);


}


/******* S.D.G. *******/



