/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div, h1, label, input, table, tbody, ul, li, tr, td, cardListItem, editedCard, newCard, deleteCard } from "../../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	return div({}, [
		h1({}, ["CARDVIEW"]),
		div({}, [
			table({class: ""}, [
				tbody({}, [
					attributes.cardList.map((item) => cardListItem(item))
				])
			])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "naturalInputOrder"
			}, ["NATURALINPUTORDER"]), 
			input({
				id: "naturalInputOrder",
				value: attributes.naturalInputOrder, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.naturalInputOrder])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "filter"
			}, ["FILTER"]), 
			input({
				id: "filter",
				value: attributes.filter, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.filter])
		]),
		editedCard(),
		newCard(),
		div({}, [
			ul({class: ""}, [
				attributes.cardDuplicates.map((item) => li({}, [item]))
			])
		]),
		deleteCard(),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "dictionaryValue"
			}, ["DICTIONARYVALUE"]), 
			input({
				id: "dictionaryValue",
				value: attributes.dictionaryValue, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.dictionaryValue])
		]),
		div({}, [
			ul({class: ""}, [
				attributes.selectedCardIds.map((item) => li({}, [item]))
			])
		]),
		div({}, [
			ul({class: ""}, [
				attributes.movedCardIds.map((item) => li({}, [item]))
			])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "dragTargetCardId"
			}, ["DRAGTARGETCARDID"]), 
			input({
				id: "dragTargetCardId",
				value: attributes.dragTargetCardId, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.dragTargetCardId])
		])
	]);
}



/******* S.D.G. *******/



