/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {
    button,
    categoryDialog,
    deleteCategoryDialog,
    div,
    i,
    inviteUserDialog,
    rootCategory
} from "../../../../../gen/components/ReactHelper";
import {
    createReverseBox,
    deleteCategoryClick,
    editCategoryClick,
    inviteUserClick,
    newCategoryClick
} from "../../../../../gen/category/ActionFunctions";
import {route} from "../../../../../gen/common/ActionFunctions";
import React from "react";
import {Texts} from "../../../../app/Texts";

export function uiElement(attributes) {

    if (!attributes.rootCategory) {
        return null;
    }

    return div({class: "categoryTree"}, [
        categoryDialog({...attributes.categoryDialog, language: attributes.language}),
        inviteUserDialog({...attributes.inviteUserDialog, language: attributes.language}),
        deleteCategoryDialog({...attributes.deleteCategoryDialog, language: attributes.language}),

        div({}, [
            button({
                onClick: () => route("#dashboard"),
                title: Texts.categoryTree.back[attributes.language]
            }, [
                i({class: "fa fa-arrow-left"})
            ]),
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => newCategoryClick(),
                    title: Texts.categoryTree.newCategory.newChildCategory[attributes.language]
                }, [
                    i({class: "fas fa-plus"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => editCategoryClick(),
                    title: Texts.categoryTree.editCategory.title[attributes.language]
                }, [
                    i({class: "fas fa-pen"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => inviteUserClick(),
                    title: Texts.categoryTree.inviteUser.title[attributes.language]
                }, [
                    i({class: "fas fa-share"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory || !attributes.selectedCategory.empty || attributes.rootCategory.categoryId === attributes.selectedCategory.categoryId,
                    onClick: () => deleteCategoryClick(),
                    title: Texts.categoryTree.delete[attributes.language]
                }, [
                    i({class: "far fa-trash-alt"})
                ]) :
                null,
            attributes.reverseBoxExists === false ?
                button({
                    onClick: () => createReverseBox(),
                    title: Texts.categoryTree.createReverseBox[attributes.language]
                }, [
                    i({class: "fas fa-plus-circle"})
                ]) :
                null,
        ]),

        div({class: "categoryTreeItems"}, [
            rootCategory({
                ...attributes.rootCategory,
                selectedCategory: attributes.selectedCategory,
                language: attributes.language,
                dropAllowed: attributes.dropAllowed && attributes.rootCategory.editable,
                dropTargetCategoryId: attributes.dropTargetCategoryId,
            })
        ]),
    ]);
}


/******* S.D.G. *******/



