/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {
    button, categoryDialog,
    div,
    h2,
    i,
    input, inviteUserDialog,
    rootCategory,
    table,
    tbody,
    td,
    th,
    thead,
    tr
} from "../../../../../gen/components/ReactHelper";
import {
    cancelNewCategory,
    cancelPreviewCsv,
    categoryNameChanged,
    createCategory, deleteCategoryClick,
    editCategoryClick,
    importCsv, inviteUserClick,
    newCategoryClick,
    previewCsv,
    swapPreviewCsv
} from "../../../../../gen/category/ActionFunctions";
import {route} from "../../../../../gen/common/ActionFunctions";
import React from "react";
import {Texts} from "../../../../app/Texts";

export function uiElement(attributes) {
    const onCsvFileChange = (event) => {
        let files = event.target.files;

        if (files.length > 0) {
            const file = files[0];
            event.target.value = null;
            let reader = new FileReader();
            reader.onload = function () {
                previewCsv(reader.result);
            };
            reader.readAsText(file);
        }
    }

    const csvPreview = () => {
        let csv = attributes.previewCsv.map((row) => {
            return tr({key: row[2]}, [
                td({}, [row[0]]),
                td({}, [row[1]]),
            ]);
        });
        return div({class: "modal"}, [
            div({class: "modalContent"}, [
                h2({}, [Texts.categoryTree.csvPreview.title[attributes.language]]),
                table({}, [
                    thead({}, [
                        tr({}, [
                            th({}, [
                                Texts.categoryTree.csvPreview.given[attributes.language],
                                attributes.selectedCategory.attributes ? ' (' + Texts.categoryTree.csvPreview.languages[attributes.selectedCategory.attributes][attributes.language] + ')' : ""
                            ]),
                            th({}, [
                                Texts.categoryTree.csvPreview.wanted[attributes.language],
                                attributes.selectedCategory.wantedLanguage ? ' (' + Texts.categoryTree.csvPreview.languages[attributes.selectedCategory.wantedLanguage][attributes.language] + ')' : ""
                            ]),
                        ])
                    ]),
                    tbody({}, [csv])
                ]),
                button({
                    onClick: () => swapPreviewCsv()
                }, [Texts.categoryTree.csvPreview.swap[attributes.language]]),
                button({
                    onClick: () => importCsv()
                }, [Texts.categoryTree.csvPreview.ok[attributes.language]]),
                button({
                    onClick: () => cancelPreviewCsv()
                }, [Texts.categoryTree.csvPreview.cancel[attributes.language]])
            ])
        ]);
    }

    if (!attributes.rootCategory) {
        return null;
    }

    return div({class: "categoryTree"}, [
        attributes.previewCsv && attributes.previewCsv.length > 0 && attributes.rootCategory.editable ?
            csvPreview() : null,
        categoryDialog({...attributes.categoryDialog, language: attributes.language}),
        inviteUserDialog({...attributes.inviteUserDialog, language: attributes.language}),

        div({}, [
            button({
                onClick: () => route("#dashboard"),
                title: Texts.categoryTree.back[attributes.language]
            }, [
                i({class: "fa fa-arrow-left"})
            ]),
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => newCategoryClick(),
                    title: Texts.categoryTree.newCategory.newChildCategory[attributes.language]
                }, [
                    i({class: "fas fa-plus"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => editCategoryClick(),
                    title: Texts.categoryTree.editCategory.title[attributes.language]
                }, [
                    i({class: "fas fa-pen"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory,
                    onClick: () => inviteUserClick(),
                    title: Texts.categoryTree.inviteUser.title[attributes.language]
                }, [
                    i({class: "fas fa-share"})
                ]) :
                null,
            attributes.rootCategory.editable ?
                button({
                    disabled: !attributes.selectedCategory || !attributes.selectedCategory.empty,
                    onClick: () => deleteCategoryClick(),
                    title: Texts.categoryTree.delete[attributes.language]
                }, [
                    i({class: "far fa-trash-alt"})
                ]) :
                null,
        ]),

        div({class: "categoryTreeItems"}, [
            rootCategory({
                ...attributes.rootCategory,
                childCategories: attributes.rootCategory.childCategories,
                selectedCategory: attributes.selectedCategory,
                texts: attributes.texts,
                language: attributes.language,
                key: attributes.rootCategory.categoryId,
                dropAllowed: attributes.dropAllowed && attributes.rootCategory.editable,
                dropTargetCategoryId: attributes.dropTargetCategoryId,
            })
        ]),
    ]);
}


/******* S.D.G. *******/



