/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {route} from "../../../../../../gen/common/ActionFunctions";


export const CardDuplicatesItem = (props) => {
	const renderGiven = () => {
		return <td>
			<pre>{props.given}</pre>
		</td>
	}

	const renderWanted = () => {
		return <td>
			<pre>{props.wanted}</pre>
		</td>
	}
	const renderPath = () => {
		return <td colSpan={2}>
			<a onClick={() => route(`#categories/${props.rootCategoryId}/${props.categoryId}`)}>
				{props.categoryName}
			</a>
		</td>
	}

	return <tr className="notPrinted">
		<td/>
		{props.naturalInputOrder === true ? renderGiven() : renderWanted()}
		{props.naturalInputOrder === true ? renderWanted() : renderGiven()}
		{renderPath()}
	</tr>
}



/******* S.D.G. *******/



