/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {
    div,
    h1,
    label,
    input,
    table,
    tbody,
    ul,
    li,
    tr,
    td, a,
    button, i, textarea, pre
} from "../../../../../../gen/components/ReactHelper";
import {
    deleteCardClick,
    editCard,
    givenOfEditedCardChanged,
    toggleScheduleCardSelection, wantedOfEditedCardChanged
} from "../../../../../../gen/card/ActionFunctions";
import {Texts} from "../../../../../app/Texts";
import React from "react";
import {route} from "../../../../../../gen/common/ActionFunctions";

export function uiElement(attributes) {
    const renderGiven = () => {
        return td({}, [
            pre({}, [attributes.given])
        ]);
    }

    const renderWanted = () => {
        return td({}, [
            pre({}, [attributes.wanted])
        ]);
    }
    const renderPath = () => {
        return td({colSpan: "2"}, [
            a({
                onClick: () => route(`#categories/${attributes.rootCategoryId}/${attributes.categoryId}`)
            }, [attributes.categoryName]),
        ]);
    }


    return tr({
        class: "notPrinted"
    }, [
        td({}),
        attributes.naturalInputOrder === true ? renderGiven() : renderWanted(),
        attributes.naturalInputOrder === true ? renderWanted() : renderGiven(),
        renderPath()
    ]);
}


/******* S.D.G. *******/



