/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/





import { div, h1, label, input, table, tbody, ul, li, tr, td } from "../../../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	return div({}, [
		h1({}, ["DELETECARD"]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "confirmDelete"
			}, ["CONFIRMDELETE"]), 
			input({
				id: "confirmDelete",
				value: attributes.confirmDelete, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.confirmDelete])
		]),
		div({class: ""}, [
			label({
				class: "",
				htmlFor: "cardId"
			}, ["CARDID"]), 
			input({
				id: "cardId",
				value: attributes.cardId, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.cardId])
		])
	]);
}



/******* S.D.G. *******/



