/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import {
	div,
	h1,
	label,
	input,
	table,
	tbody,
	ul,
	li,
	tr,
	td,
	h2,
	button
} from "../../../../../../gen/components/ReactHelper";
import {Texts} from "../../../../../app/Texts";
import {cancelDeleteCategory, deleteCategory} from "../../../../../../gen/category/ActionFunctions";
import {cancelDeleteCard, deleteCard} from "../../../../../../gen/card/ActionFunctions";

export function uiElement(attributes) {
	if (attributes.confirmDelete === true) {
		return div({class: "modal"}, [
			div({class: "modalContent"}, [
				h2({}, [Texts.cardList.confirmDelete.title[attributes.language]]),
				div({class: "message"}, [Texts.cardList.confirmDelete.message[attributes.language]]),
				button({
					class: "yes danger",
					onClick: () => deleteCard()
				}, [Texts.cardList.confirmDelete.ok[attributes.language]]),
				button({
					onClick: () => cancelDeleteCard()}, [Texts.cardList.confirmDelete.cancel[attributes.language]])
			])
		]);
	}
	return null;}



/******* S.D.G. *******/



