/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {
	cancelNewCard,
	createCard,
	givenOfNewCardChanged,
	passValueToDictionary,
	wantedOfNewCardChanged
} from "../../../../../../gen/card/ActionFunctions";
import {Texts} from "../../../../../app/Texts";


export const NewCard = (props) => {
	const onAltKeyUp = (e) => {
		e.preventDefault();
		if (e.keyCode === 13 && e.altKey && isValid()) {
			onCreate();
		}
		if (e.keyCode === 27) {
			onCancel();
		}
	}

	const onCreate = () => {
		createCard();
		document.getElementById(props.naturalInputOrder === true ? "given" : "wanted").focus();
	}

	const onCancel = () => {
		cancelNewCard();
		document.getElementById(props.naturalInputOrder === true ? "given" : "wanted").focus();
	}

	const onBlurGiven = () => {
		if (props.naturalInputOrder === true && !!props.dictionaryLookup && (!props.wanted || props.wanted.length === 0)) {
			passValueToDictionary();
		}
	}

	const onBlurWanted = () => {
		if (props.naturalInputOrder === false && !!props.dictionaryLookup && (!props.given || props.given.length === 0)) {
			passValueToDictionary();
		}
	}

	const renderGiven = () => {
		return <td className="textarea input">
            <textarea
				onChange={(event) => givenOfNewCardChanged(event.target.value)}
				autoComplete="off"
				value={props.given}
				placeholder={`${Texts.cardList.given[props.language]} ${props.dictionaryLookup ? "(" + Texts.categoryList.languages[props.givenLanguage][props.language] + ")" : ""}`}
				onKeyUp={onAltKeyUp}
				onBlur={onBlurGiven}
				id="given"
			/>
		</td>
	}

	const renderWanted = () => {
		return <td className="textarea input">
            <textarea
				onChange={(event) => wantedOfNewCardChanged(event.target.value)}
				autoComplete="off"
				value={props.wanted}
				placeholder={`${Texts.cardList.wanted[props.language]} ${props.dictionaryLookup ? "(" + Texts.categoryList.languages[props.wantedLanguage][props.language] + ")" : ""}`}
				onKeyUp={onAltKeyUp}
				onBlur={onBlurWanted}
				id="wanted"
			/>
		</td>
	}

	const isValid = () => {
		return props.given && props.given.length > 0 && (props.wanted && props.wanted.length > 0 || props.image.length > 0);
	}
	return <tr className="notPrinted inputRow">
		<td/>
		{props.naturalInputOrder === true ? renderGiven() : renderWanted()}
		{props.naturalInputOrder === true ? renderWanted() : renderGiven()}
		<td className="top">
			{props.displaySpinner ? <i className="fas fa-cog fa-spin"/> : null}
		</td>
		<td className="noBreak input">
			<button
				disabled={!isValid()}
				onClick={onCreate}
			>
				<i className="fas fa-check"/>
			</button>
			<button
				onClick={onCancel}
			>
				<i className="fas fa-times"/>
			</button>
		</td>
	</tr>
}



/******* S.D.G. *******/



