/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/

import * as CommonActionIds from "../gen/common/CommonActionIds";


export function getCypressFor(action, args) {
    if (CommonActionIds.init === action) {
        return cy.visit("http://127.0.0.1:8888/#")
    }
}

export function wait(numberOfSyncCalls, numberOfAsyncCalls) {
    return cy.wait(numberOfSyncCalls * 5 + numberOfAsyncCalls * 100);
}

export function testId() {
    let d = new Date().getTime();
    return 'xxxxxxxx'.replace(/[xy]/g, function (c) {
        let r = (d + Math.random() * 16) % 16 | 0;
        d = Math.floor(d / 16);
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
}


/******* S.D.G. *******/




