/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




export function loginDataWasSetInLocalStorage(testId) {
	assert.fail("loginDataWasSetInLocalStorage not implemented");
}



/******* S.D.G. *******/


