/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




export function loginDataWasSetInLocalStorage(testId) {
	expect(localStorage.getItem("username"), "username in local storage").to.eql(`username-${testId}`);
	expect(localStorage.getItem("password"), "password in local storage").to.eql("5f4dcc3b5aa765d61d8327deb882cf99");
}



/******* S.D.G. *******/


