/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




export function loginDataWasNotSetInLocalStorage() {
	expect(localStorage.getItem("username"), "username").to.eql(null);
	expect(localStorage.getItem("password"), "password").to.eql(null);
}



/******* S.D.G. *******/


