/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteBoxCommand from "../../../gen/box/commands/AbstractCancelDeleteBoxCommand";

export default class CancelDeleteBoxCommand extends AbstractCancelDeleteBoxCommand {
    execute(data) {
        data.confirmDelete = false;
        data.boxId = undefined;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



