/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateRootCategoryCommand from "../../../gen/box/commands/AbstractCreateRootCategoryCommand";

export default class CreateRootCategoryCommand extends AbstractCreateRootCategoryCommand {

    validateCommandData(data) {
        if (data.dictionaryLookup === false) {
            data.givenLanguage = null;
            data.wantedLanguage = null;
        }
        return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/
