/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteBoxCommand from "../../../gen/box/commands/AbstractDeleteBoxCommand";

export default class DeleteBoxCommand extends AbstractDeleteBoxCommand {

    validateCommandData(data) {
    	//data.boxId is mandatory String
    	return true;
    }

    handleResponse(data, resolve) {
        data.confirmDelete = false;
        data.boxId = undefined;
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve) {
        this.addErrorOutcome(data);
        data.confirmDelete = false;
        data.boxId = undefined;
        data.message = data.error;
        resolve(data);
    }
}


/******* S.D.G. *******/



