/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDictionaryLookupChangedCommand from "../../../gen/box/commands/AbstractDictionaryLookupChangedCommand";

export default class DictionaryLookupChangedCommand extends AbstractDictionaryLookupChangedCommand {
    execute(data) {
        data.dictionaryLookup = !data.dictionaryLookup;
        if (data.dictionaryLookup === true) {
            data.dictionaryLookupInvalid = !data.givenLanguage || !data.wantedLanguage;
        } else {
            data.dictionaryLookupInvalid = false;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



