/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGivenLanguageChangedCommand from "../../../gen/box/commands/AbstractGivenLanguageChangedCommand";

export default class GivenLanguageChangedCommand extends AbstractGivenLanguageChangedCommand {
    execute(data) {
        if (data.dictionaryLookup === true) {
            data.dictionaryLookupInvalid = !data.givenLanguage || !data.wantedLanguage;
        } else {
            data.dictionaryLookupInvalid = false;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



