/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitBoxesForDayDuringScoreCommand from "../../../gen/box/commands/AbstractInitBoxesForDayDuringScoreCommand";

export default class InitBoxesForDayDuringScoreCommand extends AbstractInitBoxesForDayDuringScoreCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



