/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractLoadActiveCardsCommand from "../../../gen/box/commands/AbstractLoadActiveCardsCommand";

export default class LoadActiveCardsCommand extends AbstractLoadActiveCardsCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.addOkOutcome();
    	this.commandData.selectedCardIds = [];
    	this.commandData.activeCardList = this.commandData.cardList;
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



