/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadBoxesCommand from "../../../gen/box/commands/AbstractLoadBoxesCommand";

export default class LoadBoxesCommand extends AbstractLoadBoxesCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        data.dashboardView = {
            boxList: data.boxList,
            deleteBox: {
                confirmDelete: false,
                boxId: undefined
            }
        };
        data.boxList = undefined;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



