/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadSettingsCommand from "../../../gen/box/commands/AbstractLoadSettingsCommand";

export default class LoadSettingsCommand extends AbstractLoadSettingsCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        data.maxCardsPerDay = data.maxCardsPerDay ? data.maxCardsPerDay : "";
        data.maxInterval = data.maxInterval ? data.maxInterval : "";
        data.tooManyCardsWarning = !!(data.maxCardsPerDay && data.maxInterval && data.allActiveCards > data.maxCardsPerDay * data.maxInterval);
        data.givenLanguage = !data.givenLanguage ? "": data.givenLanguage;
        data.wantedLanguage = !data.wantedLanguage ? "": data.wantedLanguage;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



