/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadBoxStatisticsCommand from "../../../gen/box/commands/AbstractLoadBoxStatisticsCommand";

export default class LoadBoxStatisticsCommand extends AbstractLoadBoxStatisticsCommand {

    validateCommandData(data) {
    	//data.todayAtMidnightInUTC is mandatory DateTime
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.boxList.forEach((box) => {
            const boxWithStats = data.boxStatisticsList.find((bs) => {
                return bs.boxId === box.boxId;
            });
            box.countsPerDayNextWeek = boxWithStats.countsPerDayNextWeek;
            box.maxCardsPerDay = boxWithStats.maxCardsPerDay;
            box.quality0Count = boxWithStats.quality0Count;
            box.quality1Count = boxWithStats.quality1Count;
            box.quality2Count = boxWithStats.quality2Count;
            box.quality3Count = boxWithStats.quality3Count;
            box.quality4Count = boxWithStats.quality4Count;
            box.quality5Count = boxWithStats.quality5Count;
        });
        data.boxStatisticsList = undefined;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



