/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadActiveCardsCommand from "../../../gen/box/commands/AbstractLoadActiveCardsCommand";

export default class LoadActiveCardsCommand extends AbstractLoadActiveCardsCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve, reject) {
        data.selectedCardIds = [];
        data.activeCardList = data.cardList;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



