/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMaxCardsPerDayChangedCommand from "../../../gen/box/commands/AbstractMaxCardsPerDayChangedCommand";

export default class MaxCardsPerDayChangedCommand extends AbstractMaxCardsPerDayChangedCommand {
    execute(data) {
        data.maxCardsPerDayInvalid = !data.maxCardsPerDay
            || isNaN(data.maxCardsPerDay)
            || data.maxCardsPerDay%1 !== 0
            || data.maxCardsPerDay <= 0;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



