/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRootCategoryNameChangedCommand from "../../../gen/box/commands/AbstractRootCategoryNameChangedCommand";

export default class RootCategoryNameChangedCommand extends AbstractRootCategoryNameChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



