/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSaveBoxSettingsCommand from "../../../gen/box/commands/AbstractSaveBoxSettingsCommand";

export default class SaveBoxSettingsCommand extends AbstractSaveBoxSettingsCommand {

    validateCommandData(data) {
        if (data.dictionaryLookup === false) {
            data.givenLanguage = null;
            data.wantedLanguage = null;
        }
        return true;
    }

    handleResponse(data, resolve, reject) {
        data.dictionaryLookup = undefined;
        data.givenLanguage = undefined;
        data.wantedLanguage = undefined;
        data.boxId = undefined;
        data.maxInterval = undefined;
        data.maxCardsPerDay = undefined;
        data.categoryId = undefined;
        data.categoryName = undefined;
        data.hash = "#dashboard";
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/

