/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractScheduleSelectedCardsCommand from "../../../gen/box/commands/AbstractScheduleSelectedCardsCommand";

export default class ScheduleSelectedCardsCommand extends AbstractScheduleSelectedCardsCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.addNoFilterOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



