/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractScoreReinforceCardCommand from "../../../gen/box/commands/AbstractScoreReinforceCardCommand";

export default class ScoreReinforceCardCommand extends AbstractScoreReinforceCardCommand {

    validateCommandData(data) {
    	//data.reinforceCardId is mandatory String
    	//data.keep is mandatory Boolean
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



