/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractScoreCardCommand from "../../../gen/box/commands/AbstractScoreCardCommand";

export default class ScoreCardCommand extends AbstractScoreCardCommand {

    validateCommandData(data) {
    	//data.scheduledCardId is mandatory String
    	//data.scoredCardQuality is mandatory Integer
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



