/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSortCardOutCommand from "../../../gen/box/commands/AbstractSortCardOutCommand";

export default class SortCardOutCommand extends AbstractSortCardOutCommand {

    validateCommandData(data) {
        data.cardIds = [];
        data.cardIds[0] = data.cardId;
        return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



