/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleScheduleCardSelectionCommand from "../../../gen/box/commands/AbstractToggleScheduleCardSelectionCommand";

export default class ToggleScheduleCardSelectionCommand extends AbstractToggleScheduleCardSelectionCommand {
    execute(data) {
        const index = data.selectedCardIds.indexOf(data.cardId);
        if (index !== -1) {
            data.selectedCardIds.splice(index, 1);
        } else {
            data.selectedCardIds.push(data.cardId);
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



