/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractTooManyCardsStatusCommand from "../../../gen/box/commands/AbstractTooManyCardsStatusCommand";

export default class TooManyCardsStatusCommand extends AbstractTooManyCardsStatusCommand {
    execute() {
        if (this.commandData.maxInterval === "" || this.commandData.maxCardsPerDay === "" || !this.commandData.allActiveCards || this.commandData.allActiveCards === 0) {
            this.commandData.tooManyCardsStatus = 0;
        } else if (this.commandData.maxCardsPerDay && this.commandData.allActiveCards > this.commandData.maxCardsPerDay * this.commandData.maxInterval) {
            this.commandData.tooManyCardsStatus = 2;
        } else {
            this.commandData.tooManyCardsStatus = 1;
        }
        this.addOkOutcome();
    }
}




/******* S.D.G. *******/



