/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractUpdateCardPriorityCommand from "../../../gen/box/commands/AbstractUpdateCardPriorityCommand";

export default class UpdateCardPriorityCommand extends AbstractUpdateCardPriorityCommand {

    validateCommandData() {
    	//this.commandData.cardId is mandatory String
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.error);
    }
}




/******* S.D.G. *******/



