/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelVersionMismatchDialogCommand from "../../../gen/common/commands/AbstractCancelVersionMismatchDialogCommand";

export default class CancelVersionMismatchDialogCommand extends AbstractCancelVersionMismatchDialogCommand {
    execute(data) {
        data.display = false;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



