/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractCancelVersionMismatchDialogCommand from "../../../gen/common/commands/AbstractCancelVersionMismatchDialogCommand";

export default class CancelVersionMismatchDialogCommand extends AbstractCancelVersionMismatchDialogCommand {
    execute() {
        this.commandData.display = false;
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



