/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractClickToastCommand from "../../../gen/common/commands/AbstractClickToastCommand";

export default class ClickToastCommand extends AbstractClickToastCommand {
    execute() {
        const index = this.commandData.messages.findIndex((m) => m.id === this.commandData.id );
        if (index >= 0) {
            this.addOkOutcome();
        } else {
            this.addNotFoundOutcome();
        }
        this.addOkOutcome();
    }
}




/******* S.D.G. *******/



