/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDestroyToastCommand from "../../../gen/common/commands/AbstractDestroyToastCommand";

export default class DestroyToastCommand extends AbstractDestroyToastCommand {
    execute() {
    	this.addOkOutcome();
        const index = this.commandData.messages.findIndex(i => i.id === this.commandData.id);
        if (index >= 0) {
            this.commandData.messages.splice(index, 1);
        }
    }
}




/******* S.D.G. *******/



