/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDestroyToastCommand from "../../../gen/common/commands/AbstractDestroyToastCommand";

export default class DestroyToastCommand extends AbstractDestroyToastCommand {
    execute(data) {
        const index = data.messages.findIndex(i => i.id === data.id);
        if (index >= 0) {
            data.messages.splice(index, 1);
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



