/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchDialogCommand from "../../../gen/common/commands/AbstractDisplayVersionMismatchDialogCommand";

export default class DisplayVersionMismatchDialogCommand extends AbstractDisplayVersionMismatchDialogCommand {
    execute() {
        this.commandData.displayVersionMismatchDialog = true;
        this.addOkOutcome();
    }
}




/******* S.D.G. *******/



