/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchErrorDialogCommand from "../../../gen/common/commands/AbstractDisplayVersionMismatchErrorDialogCommand";

export default class DisplayVersionMismatchErrorDialogCommand extends AbstractDisplayVersionMismatchErrorDialogCommand {
    execute() {
        this.commandData.displayVersionMismatchErrorDialog = true;
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



