/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractDisplayToastCommand from "../../../gen/common/commands/AbstractDisplayToastCommand";

export default class DisplayToastCommand extends AbstractDisplayToastCommand {
    execute(data) {
        if (!data.message) {
            if (data.error && typeof data.error === "object") {
                data.message = data.error;
                data.message.type = "error";
            }
            data.message = {};
        }
        data.message.id = data.messages.length;
        data.message.visible = true;
        data.messages.push(data.message);
        data.id = data.message.id;
        this.addOkOutcome(data);
        return data;
    }
}


/******* S.D.G. *******/



