/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractHideToastCommand from "../../../gen/common/commands/AbstractHideToastCommand";

export default class HideToastCommand extends AbstractHideToastCommand {
    execute(data) {
        const index = data.messages.findIndex(i => i.id === data.id);
        if (index >= 0) {
            data.messages[index].visible = false;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



