/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractHideSaveBugDialogCommand from "../../../gen/common/commands/AbstractHideSaveBugDialogCommand";
import * as AppUtils from "../../app/AppUtils";

export default class HideSaveBugDialogCommand extends AbstractHideSaveBugDialogCommand {
    execute(data) {
        data.display = false;
        data.message = AppUtils.createInfoMessage("thankYou");
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



