/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitialLoginCommand from "../../../gen/common/commands/AbstractInitialLoginCommand";
import * as AppUtils from "../../app/AppUtils";

export default class InitialLoginCommand extends AbstractInitialLoginCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
        if (AppUtils.isUnauthorized(data.error)) {
            this.addUnauthorizedOutcome(data);
            data.message = data.error;
            resolve(data);
        } else {
            reject(data.error);
        }
    }
}




/******* S.D.G. *******/



