/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitCommand from "../../../gen/common/commands/AbstractInitCommand";

export default class InitCommand extends AbstractInitCommand {
    execute(data) {
        data.language = "de";
        data.messages = [];
        if (data.username && data.password) {
            data.loggedInUser = {
                username: data.username,
                password: data.password
            };
            this.addUserOutcome(data);
        } else {
            data.loggedInUser = null;
            this.addNoUserOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/



