/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRouteCommand from "../../../gen/common/commands/AbstractRouteCommand";

export default class RouteCommand extends AbstractRouteCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



