/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div, h1, label, input, table, tbody, ul, li, tr, td } from "../../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	return tr({class: ""}, [
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "openTodaysCards"
			}, ["OPENTODAYSCARDS"]), 
			input({
				id: "openTodaysCards",
				value: attributes.openTodaysCards, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.openTodaysCards])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "categoryName"
			}, ["CATEGORYNAME"]), 
			input({
				id: "categoryName",
				value: attributes.categoryName, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.categoryName])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "categoryId"
			}, ["CATEGORYID"]), 
			input({
				id: "categoryId",
				value: attributes.categoryId, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.categoryId])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "boxId"
			}, ["BOXID"]), 
			input({
				id: "boxId",
				value: attributes.boxId, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.boxId])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality0Count"
			}, ["QUALITY0COUNT"]), 
			input({
				id: "quality0Count",
				value: attributes.quality0Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality0Count])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality1Count"
			}, ["QUALITY1COUNT"]), 
			input({
				id: "quality1Count",
				value: attributes.quality1Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality1Count])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality2Count"
			}, ["QUALITY2COUNT"]), 
			input({
				id: "quality2Count",
				value: attributes.quality2Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality2Count])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality3Count"
			}, ["QUALITY3COUNT"]), 
			input({
				id: "quality3Count",
				value: attributes.quality3Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality3Count])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality4Count"
			}, ["QUALITY4COUNT"]), 
			input({
				id: "quality4Count",
				value: attributes.quality4Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality4Count])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "quality5Count"
			}, ["QUALITY5COUNT"]), 
			input({
				id: "quality5Count",
				value: attributes.quality5Count, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.quality5Count])
		]),
		td({}, [
			ul({class: ""}, [
				attributes.countsPerDayNextWeek.map((item) => li({}, [item]))
			])
		]),
		td({class: ""}, [
			label({
				class: "",
				htmlFor: "maxCardsPerDay"
			}, ["MAXCARDSPERDAY"]), 
			input({
				id: "maxCardsPerDay",
				value: attributes.maxCardsPerDay, 
				class: "", 
				onChange:(e) => console.log(e.target.value),
				type: "text"
			}), 
			div({class: ""}, [attributes.maxCardsPerDay])
		])
	]);
}



/******* S.D.G. *******/



