/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../app/Texts";
import {cancelDeleteBox, deleteBox} from "../../../../../gen/box/ActionFunctions";


export const DeleteBox = (props) => {
	if (props.confirmDelete === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{Texts.box.confirmDelete.title[props.language]}</h2>
				<div className="message">{Texts.box.confirmDelete.message[props.language]}</div>
				<button
					className="yes danger"
					onClick={deleteBox}
				>
					{Texts.box.confirmDelete.ok[props.language]}
				</button>
				<button
					onClick={cancelDeleteBox}
				>
					{Texts.box.confirmDelete.cancel[props.language]}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



