/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {button, div, h2} from "../../../../../gen/components/ReactHelper";
import {Texts} from "../../../../app/Texts";
import {cancelDeleteBox, deleteBox} from "../../../../../gen/box/ActionFunctions";

export function uiElement(attributes) {
	if (attributes.confirmDelete === true) {
		return div({class: "modal"}, [
			div({class: "modalContent"}, [
				h2({}, [Texts.box.confirmDelete.title[attributes.language]]),
				div({class: "message"}, [Texts.box.confirmDelete.message[attributes.language]]),
				button({class: "yes danger", onClick: () => deleteBox()}, [Texts.box.confirmDelete.ok[attributes.language]]),
				button({onClick: () => cancelDeleteBox()}, [Texts.box.confirmDelete.cancel[attributes.language]])
			])
		]);
	}
	return null;
}



/******* S.D.G. *******/



