/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteCardCommand from "../../../gen/card/commands/AbstractCancelDeleteCardCommand";

export default class CancelDeleteCardCommand extends AbstractCancelDeleteCardCommand {
    execute(data) {
        data.deleteCard = {
            confirmDelete: false,
            cardId: ""
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



