/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelEditCardCommand from "../../../gen/card/commands/AbstractCancelEditCardCommand";

export default class CancelEditCardCommand extends AbstractCancelEditCardCommand {
    execute(data) {
        data.editedCard = {
            cardId: "",
            given: "",
            wanted: "",
            image: ""
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



