/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractChangeCardOrderCommand from "../../../gen/card/commands/AbstractChangeCardOrderCommand";

export default class ChangeCardOrderCommand extends AbstractChangeCardOrderCommand {

    validateCommandData(data) {
        data.cardIdList = data.movedCardIds;
    	return true;
    }

    handleResponse(data, resolve) {
        data.movedCardIds = undefined;
        data.dragTargetCardId = undefined;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/
