/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCardClickCommand from "../../../gen/card/commands/AbstractDeleteCardClickCommand";

export default class DeleteCardClickCommand extends AbstractDeleteCardClickCommand {
    execute(data) {
        data.deleteCard = {
            confirmDelete: true,
            cardId: data.cardId
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



