/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCardCommand from "../../../gen/card/commands/AbstractDeleteCardCommand";

export default class DeleteCardCommand extends AbstractDeleteCardCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        data.deleteCard = {
            confirmDelete: false,
            cardId: ""
        };
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



