/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditCardCommand from "../../../gen/card/commands/AbstractEditCardCommand";

export default class EditCardCommand extends AbstractEditCardCommand {
    execute(data) {
        const card = data.cardList.filter(c => c.cardId === data.cardId)[0];
        data.editedCard = {
            cardId: data.cardId,
            given: card.given,
            wanted: card.wanted,
            image: card.image
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



