/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractFilterCardsCommand from "../../../gen/card/commands/AbstractFilterCardsCommand";

export default class FilterCardsCommand extends AbstractFilterCardsCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



