/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGivenOfEditedCardChangedCommand from "../../../gen/card/commands/AbstractGivenOfEditedCardChangedCommand";

export default class GivenOfEditedCardChangedCommand extends AbstractGivenOfEditedCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



