/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadCardsCommand from "../../../gen/card/commands/AbstractLoadCardsCommand";

export default class LoadCardsCommand extends AbstractLoadCardsCommand {

    validateCommandData(data) {
        data.categoryId = data.selectedCategory.categoryId;
    	return true;
    }

    handleResponse(data, resolve) {
        if (data.naturalInputOrder === undefined) {
            data.naturalInputOrder = data.reverse === false;
        }
        data.newCard = {
            given: "",
            wanted: "",
            image: "",
            displaySpinner: false,
        };
        data.editedCard = {
            cardId: "",
            given: "",
            wanted: "",
            image: ""
        };
        data.filter = "";
        data.dictionaryValue = null;
        data.cardDuplicates = [];
        data.selectedCardIds = [];
        data.movedCardIds = [];
        data.dragTargetCardId = null;
        data.deleteCard = {
            confirmDelete: false,
            cardId: ""
        };
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/


