/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCardsStartedCommand from "../../../gen/card/commands/AbstractMoveCardsStartedCommand";

export default class MoveCardsStartedCommand extends AbstractMoveCardsStartedCommand {
    execute(data) {
        data.movedCardIds = data.selectedCardIds;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



