/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractOnDragEnterCommand from "../../../gen/card/commands/AbstractOnDragEnterCommand";

export default class OnDragEnterCommand extends AbstractOnDragEnterCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



