/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractOnDragExitCommand from "../../../gen/card/commands/AbstractOnDragExitCommand";

export default class OnDragExitCommand extends AbstractOnDragExitCommand {
    execute(data) {
        data.dragTargetCardId = undefined;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



