/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPassValueToDictionaryCommand from "../../../gen/card/commands/AbstractPassValueToDictionaryCommand";

export default class PassValueToDictionaryCommand extends AbstractPassValueToDictionaryCommand {
    execute(data) {
        if (!!data.naturalInputOrder) {
            data.dictionaryValue = data.given;
        } else {
            data.dictionaryValue = data.wanted;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



