/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleInputOrderCommand from "../../../gen/card/commands/AbstractToggleInputOrderCommand";

export default class ToggleInputOrderCommand extends AbstractToggleInputOrderCommand {
    execute(data) {
        data.naturalInputOrder = !data.naturalInputOrder;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



