/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




import AbstractUpdateCardPriorityCommand from "../../../gen/card/commands/AbstractUpdateCardPriorityCommand";

export default class UpdateCardPriorityCommand extends AbstractUpdateCardPriorityCommand {

    validateCommandData() {
    	//this.commandData.cardId is mandatory String
    	//this.commandData.priority is mandatory Integer
    	return true;
    }

    handleResponse(resolve, reject) {
    	this.commandData.outcome = this.ok;
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.error);
    }
}




/******* S.D.G. *******/



