/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




import AbstractUpdateCardPriorityCommand from "../../../gen/card/commands/AbstractUpdateCardPriorityCommand";

export default class UpdateCardPriorityCommand extends AbstractUpdateCardPriorityCommand {

    validateCommandData() {
        if (this.commandData.priority === this.commandData.actualPriority) {
            this.commandData.priority = null;
        }
    	return true;
    }

    handleResponse(resolve) {
    	this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



