/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




import AbstractUpdateCardPriorityCommand from "../../../gen/card/commands/AbstractUpdateCardPriorityCommand";

export default class UpdateCardPriorityCommand extends AbstractUpdateCardPriorityCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(resolve) {
    	this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.message);
    }
}




/******* S.D.G. *******/



