/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCardCommand from "../../../gen/card/commands/AbstractUpdateCardCommand";

export default class UpdateCardCommand extends AbstractUpdateCardCommand {

    validateCommandData(data) {
    	return true;
    }

    handleResponse(data, resolve) {
        data.editedCard = {
            cardId: "",
            given: "",
            wanted: "",
            image: ""
        };
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



