/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractWantedOfNewCardChangedCommand from "../../../gen/card/commands/AbstractWantedOfNewCardChangedCommand";

export default class WantedOfNewCardChangedCommand extends AbstractWantedOfNewCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



