/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractWantedOfEditedCardChangedCommand from "../../../gen/card/commands/AbstractWantedOfEditedCardChangedCommand";

export default class WantedOfEditedCardChangedCommand extends AbstractWantedOfEditedCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



