/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelEditCardAction from "../../../gen/card/actions/AbstractCancelEditCardAction";

export default class CancelEditCardAction extends AbstractCancelEditCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



