/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelNewCardAction from "../../../gen/card/actions/AbstractCancelNewCardAction";

export default class CancelNewCardAction extends AbstractCancelNewCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



