/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCardAction from "../../../gen/card/actions/AbstractCreateCardAction";

export default class CreateCardAction extends AbstractCreateCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



