/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCardAction from "../../../gen/card/actions/AbstractDeleteCardAction";

export default class DeleteCardAction extends AbstractDeleteCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



