/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditCardAction from "../../../gen/card/actions/AbstractEditCardAction";

export default class EditCardAction extends AbstractEditCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



