/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractFilterCardsAction from "../../../gen/card/actions/AbstractFilterCardsAction";

export default class FilterCardsAction extends AbstractFilterCardsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



