/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGivenOfEditedCardChangedAction from "../../../gen/card/actions/AbstractGivenOfEditedCardChangedAction";

export default class GivenOfEditedCardChangedAction extends AbstractGivenOfEditedCardChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



