/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGivenOfNewCardChangedAction from "../../../gen/card/actions/AbstractGivenOfNewCardChangedAction";

export default class GivenOfNewCardChangedAction extends AbstractGivenOfNewCardChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



