/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadCardsAction from "../../../gen/card/actions/AbstractLoadCardsAction";

export default class LoadCardsAction extends AbstractLoadCardsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



