/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCardsStartedAction from "../../../gen/card/actions/AbstractMoveCardsStartedAction";

export default class MoveCardsStartedAction extends AbstractMoveCardsStartedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



