/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractMoveCardsAction from "../../../gen/card/actions/AbstractMoveCardsAction";

export default class MoveCardsAction extends AbstractMoveCardsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



