/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractOnDragEnterAction from "../../../gen/card/actions/AbstractOnDragEnterAction";

export default class OnDragEnterAction extends AbstractOnDragEnterAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



