/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractOnDragExitAction from "../../../gen/card/actions/AbstractOnDragExitAction";

export default class OnDragExitAction extends AbstractOnDragExitAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



