/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSearchDuplicateCardsAction from "../../../gen/card/actions/AbstractSearchDuplicateCardsAction";

export default class SearchDuplicateCardsAction extends AbstractSearchDuplicateCardsAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



