/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleInputOrderAction from "../../../gen/card/actions/AbstractToggleInputOrderAction";

export default class ToggleInputOrderAction extends AbstractToggleInputOrderAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



