/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




import AbstractUpdateCardPriorityAction from "../../../gen/card/actions/AbstractUpdateCardPriorityAction";

export default class UpdateCardPriorityAction extends AbstractUpdateCardPriorityAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



