/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCardAction from "../../../gen/card/actions/AbstractUpdateCardAction";

export default class UpdateCardAction extends AbstractUpdateCardAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



