/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractWantedOfEditedCardChangedAction from "../../../gen/card/actions/AbstractWantedOfEditedCardChangedAction";

export default class WantedOfEditedCardChangedAction extends AbstractWantedOfEditedCardChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



