/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractWantedOfNewCardChangedAction from "../../../gen/card/actions/AbstractWantedOfNewCardChangedAction";

export default class WantedOfNewCardChangedAction extends AbstractWantedOfNewCardChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



