/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { pre } from "../../../../../gen/components/ReactHelper";

export function uiElement(attributes) {
	const json = JSON.stringify(attributes, null, '\t');
	return pre({}, [json]);
}



/******* S.D.G. *******/



