/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

const ScenarioUtils = require("../ScenarioUtils");



module.exports = {
	loginDataWasSetInLocalStorage: async function(driver, testId) {
		expect(await ScenarioUtils.getValueFromLocalStorage(driver, "username")).toEqual(`username-${testId}`);
		expect(await ScenarioUtils.getValueFromLocalStorage(driver, "password")).toEqual("5f4dcc3b5aa765d61d8327deb882cf99");
	}
}



/******* S.D.G. *******/


