/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




module.exports = {
	loginDataWasNotSetInLocalStorage: function(testId) {
		fail("loginDataWasNotSetInLocalStorage not implemented");
	}
}



/******* S.D.G. *******/


