/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




module.exports = {
	loginDataWasSetInLocalStorage: function(testId) {
		fail("loginDataWasSetInLocalStorage not implemented");
	}
}



/******* S.D.G. *******/


