/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractForgotPasswordAction from "../../../gen/password/actions/AbstractForgotPasswordAction";

export default class ForgotPasswordAction extends AbstractForgotPasswordAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



