/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractResetPasswordAction from "../../../gen/password/actions/AbstractResetPasswordAction";

export default class ResetPasswordAction extends AbstractResetPasswordAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



