/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUsernameForgotPasswordChangedAction from "../../../gen/password/actions/AbstractUsernameForgotPasswordChangedAction";

export default class UsernameForgotPasswordChangedAction extends AbstractUsernameForgotPasswordChangedAction {

    initActionData(data) {
    }

}




/******* S.D.G. *******/



